# Dados reais de um mercado da França

In [66]:
import pandas as pd
base_mercado2 = pd.read_csv('mercado2.csv', header=None) # base não tem cabeçalho
display(base_mercado2.tail())
display(base_mercado2.head())
# nome de produtos, cada linha é uma transação de alimento, bebidas  etc.
# listagem dos produtos comprados, com 7mil dados, base de 1 semana neste mercado. 
# máxima de quantidade de produtos é de 20 para uma pessoa.

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
base_mercado2.shape

(7501, 20)

Colocar em formato de lista para manusear os dados

In [68]:
base_mercado2.shape[0]

7501

In [69]:
base_mercado2.shape[1]

20

In [70]:
base_mercado2.values[0, 0] # camarão

'shrimp'

In [71]:
transacoes = []
for i in range(base_mercado2.shape[0]):
  transacoes.append([str(base_mercado2.values[i, j]) for j in range(base_mercado2.shape[1])]) # colocar em string

In [72]:
transacoes[-1][:-3]

['eggs',
 'frozen smoothie',
 'yogurt cake',
 'low fat yogurt',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan']

In [73]:
transacoes # base de dados requeridos no projeto

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers',
  'meatballs',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['chutney',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'avocado',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'milk',
  'energy bar',
  'whole wheat rice',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['low fat yogurt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['whole wheat pasta',
  'french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['soup',
  'light cream',
  'shallot',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['frozen vegetables',
  'spaghetti',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['eggs',
  'pet food',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'burgers',
  'mineral water',
  'eggs',
  'cooking oil',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'champagne',
  'cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'salmon',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['shrimp',
  'chocolate',
  'chicken',
  'honey',
  'oil',
  'cooking oil',
  'low fat yogurt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'fresh tuna',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'black tea',
  'salmon',
  'eggs',
  'chicken',
  'extra dark chocolate',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['meatballs',
  'milk',
  'honey',
  'french fries',
  'protein bar',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['red wine',
  'shrimp',
  'pasta',
  'pepper',
  'eggs',
  'chocolate',
  'shampoo',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['rice',
  'sparkling water',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'mineral water',
  'ham',
  'body spray',
  'pancakes',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'grated cheese',
  'shrimp',
  'pasta',
  'avocado',
  'honey',
  'white wine',
  'toothpaste',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['parmesan cheese',
  'spaghetti',
  'soup',
  'avocado',
  'milk',
  'fresh bread',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'energy bar',
  'black tea',
  'salmon',
  'frozen smoothie',
  'escalope',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['sparkling water',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'eggs',
  'chicken',
  'chocolate',
  'french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['frozen vegetables',
  'spaghetti',
  'yams',
  'mineral water',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['herb & pepper',
  'tomato sauce',
  'light cream',
  'magazines',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'chocolate',
  'avocado',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'french fries',
  'strawberries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['frozen vegetables',
  'strong cheese',
  'chocolate',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['pickles',
  'spaghetti',
  'salmon',
  'escalope',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['energy bar',
  'french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['red wine',
  'ground beef',
  'mineral water',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'cake',
  'cottage cheese',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['pickles',
  'champagne',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['fresh tuna',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'honey',
  'whole wheat rice',
  'frozen smoothie',
  'escalope',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['soup',
  'meatballs',
  'hot dogs',
  'sparkling water',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['escalope',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['soup',
  'avocado',
  'french fries',
  'hot dogs',
  'brownies',
  'body spray',
  'pancakes',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'chicken',
  'cereals',
  'clothes accessories',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'bug spray',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['avocado',
  'muffins',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'black tea',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'chocolate',
  'brownies',
  'white wine',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['fresh tuna',
  'mineral water',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'muffins',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'chocolate',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['french fries',
  'escalope',
  'champagne',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['tomato sauce',
  'light mayo',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'fresh tuna',
  'frozen vegetables',
  'tomatoes',
  'ground beef',
  'spaghetti',
  'mineral water',
  'chocolate',
  'soup',
  'milk',
  'olive oil',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['eggs',
  'cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['soup',
  'chicken',
  'gums',
  'soda',
  'body spray',
  'energy drink',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'frozen vegetables',
  'mineral water',
  'cider',
  'cooking oil',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['spaghetti',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['clothes accessories',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['energy drink',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['soup',
  'bug spray',
  'shallot',
  'protein bar',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['chocolate',
  'milk',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'avocado',
  'cider',
  'whole wheat rice',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['shrimp',
  'pasta',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['grated cheese',
  'herb & pepper',
  'tomatoes',
  'tomato sauce',
  'corn',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'escalope',
  'shallot',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['yogurt cake',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['soup',
  'eggs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'chocolate',
  'low fat yogurt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['eggs',
  'strawberries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['grated cheese',
  'ground beef',
  'spaghetti',
  'mineral water',
  'white wine',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mint',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['eggs',
  'cake',
  'french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'spaghetti',
  'milk',
  'french fries',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['mineral water',
  'energy bar',
  'butter',
  'french fries',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'eggs',
  'cooking oil',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['energy bar',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['energy bar',
  'energy drink',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['chocolate',
  'frozen smoothie',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['low fat yogurt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['asparagus',
  'salad',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'french fries',
  'low fat yogurt',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['low fat yogurt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'herb & pepper',
  'shrimp',
  'pasta',
  'spaghetti',
  'mineral water',
  'meatballs',
  'olive oil',
  'energy bar',
  'french wine',
  'eggs',
  'salt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['champagne',
  'low fat yogurt',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['champagne',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['burgers',
  'almonds',
  'eggs',
  'french fries',
  'cookies',
  'green tea',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['ham',
  'soup',
  'escalope',
  'body spray',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['turkey',
  'ham',
  'frozen vegetables',
  'pepper',
  'oil',
  'extra dark chocolate',
  'tea',
  'magazines',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['muffins',
  'eggs',
  'cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['cookies',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',

- min_support = 0.3

Suporte (Support) mede a frequência com que um conjunto de itens (itemset) aparece em todas as suas transações.

min_support = 0.3 significa que a regra só será considerada se os itens nela aparecerem juntos em pelo menos 30% de todas as transações. É um filtro para garantir que você só trabalhe com conjuntos de itens que são realmente populares.

- min_confidence = 0.8

Confiança (Confidence) mede a probabilidade de um item ser comprado, dado que outro item já foi comprado.

 min_confidence = 0.8 significa que a regra só será considerada se houver 80% de chance de um cliente comprar o segundo item, sabendo que ele já comprou o primeiro. É um filtro para garantir a confiabilidade da regra.

- min_lift = 2

Lift (Elevação) é a métrica mais poderosa, pois ela mede a força real da associação. Ela compara a probabilidade de os itens serem comprados juntos com a probabilidade de eles serem comprados de forma independente (por acaso).

 min_lift = 2 significa que a regra só será considerada se os itens forem pelo menos duas vezes mais propensos a serem comprados juntos do que seriam por acaso. É um filtro para eliminar associações óbvias ou sem sentido, encontrando padrões verdadeiramente surpreendentes e importantes.



regras de associação que são populares (min_support), confiáveis (min_confidence) e fortes/relevantes (min_lift).

In [74]:
from apyori import apriori
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8, min_lift = 2)
regras

In [75]:
resultados = list(regras)
len(resultados) # gerado 0 regras, base de dados muito grande

0


### suport, porcentagem que ocorreu, precisa diminuir

Definir um objetivo, com regras de associação , para produtos que são vendidos 4 vezes ao dia

In [76]:
# Produtos que são vendidos 4 vezes por dia
print(4 * 7)

28

In [77]:
n_vezes_vendas = 4
semana_dia = 7

compras = n_vezes_vendas*semana_dia

print(compras)

28

In [78]:
qtd_pessoas_comprou_local = len(base_mercado2)
print(qtd_pessoas_comprou_local)

7501

In [79]:

# divisão de produtos vendidos/ quantidades totais de produtos 
print(compras/qtd_pessoas_comprou_local) # valor que é a base para o suporte na regra apriori
# valor os produtos que são vendidos 4 vezes ao dia, na nossa base de dados

0.0037328356219170776

In [80]:
28 / 7501

0.0037328356219170776

In [81]:
regras = apriori(transacoes, min_support = 0.003, min_confidence = 0.8, min_lift = 2)
resultados = list(regras)
len(resultados)
# deu zero, então temos que diminuir o valor de confiança, comum em dados muito grande

0

In [82]:
regras = apriori(transacoes, min_support = 0.003, min_confidence = 0.2, min_lift = 2)
resultados = list(regras)
len(resultados)
# diminuido o suporte e a confiança

689

In [83]:
regras = apriori(transacoes, min_support = 0.003, min_confidence = 0.2, min_lift = 3)
resultados = list(regras)
len(resultados)
# diminuido o suporte e a confiança, e aumentar o lift, na filtragem

160

In [84]:
import prettyprinter as pp
pp.pprint(resultados)
print('\nquantidade de dados:', len(resultados)) # quantidade de dados diminuiram

[
    apyori.RelationRecord(
        items=frozenset(['light cream', 'chicken']),
        support=0.004532728969470737,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['light cream']),
                items_add=frozenset(['chicken']),
                confidence=0.29059829059829057,
                lift=4.84395061728395
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['escalope', 'mushroom cream sauce']),
        support=0.005732568990801226,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['mushroom cream sauce']),
                items_add=frozenset(['escalope']),
                confidence=0.3006993006993007,
                lift=3.790832696715049
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['escalope', 'pasta']),
        support=0.005865884548726837,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['pasta']),
                items_add=frozenset(['escalope']),
                confidence=0.3728813559322034,
                lift=4.700811850163794
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['honey', 'fromage blanc']),
        support=0.003332888948140248,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['fromage blanc']),
                items_add=frozenset(['honey']),
                confidence=0.2450980392156863,
                lift=5.164270764485569
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['ground beef', 'herb & pepper']),
        support=0.015997866951073192,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['herb & pepper']),
                items_add=frozenset(['ground beef']),
                confidence=0.3234501347708895,
                lift=3.2919938411349285
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['tomato sauce', 'ground beef']),
        support=0.005332622317024397,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['tomato sauce']),
                items_add=frozenset(['ground beef']),
                confidence=0.3773584905660377,
                lift=3.840659481324083
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['olive oil', 'light cream']),
        support=0.003199573390214638,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['light cream']),
                items_add=frozenset(['olive oil']),
                confidence=0.20512820512820515,
                lift=3.1147098515519573
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['whole wheat pasta', 'olive oil']),
        support=0.007998933475536596,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['whole wheat pasta']),
                items_add=frozenset(['olive oil']),
                confidence=0.2714932126696833,
                lift=4.122410097642296
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['shrimp', 'pasta']),
        support=0.005065991201173177,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['pasta']),
                items_add=frozenset(['shrimp']),
                confidence=0.3220338983050847,
                lift=4.506672147735896
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'avocado', 'spaghetti']),
        support=0.003332888948140248,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['avocado', 'spaghetti']),
                items_add=frozenset(['milk']),
                confidence=0.41666666666666663,
                lift=3.215449245541838
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'cake', 'burgers']),
        support=0.0037328356219170776,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['milk', 'cake']),
                items_add=frozenset(['burgers']),
                confidence=0.27999999999999997,
                lift=3.211437308868501
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['chocolate', 'burgers', 'turkey']),
        support=0.0030662578322890282,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['chocolate', 'turkey']),
                items_add=frozenset(['burgers']),
                confidence=0.27058823529411763,
                lift=3.1034898363014927
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'burgers', 'turkey']),
        support=0.003199573390214638,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['milk', 'turkey']),
                items_add=frozenset(['burgers']),
                confidence=0.2823529411764706,
                lift=3.2384241770102533
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['frozen vegetables', 'cake', 'tomatoes']),
        support=0.0030662578322890282,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'cake']),
                items_add=frozenset(['tomatoes']),
                confidence=0.2987012987012987,
                lift=4.367560314928736
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['cake', 'tomatoes']),
                items_add=frozenset(['frozen vegetables']),
                confidence=0.36507936507936506,
                lift=3.8300144300144296
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['ground beef', 'cereals', 'spaghetti']),
        support=0.0030662578322890282,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['ground beef', 'cereals']),
                items_add=frozenset(['spaghetti']),
                confidence=0.6764705882352942,
                lift=3.8853031258445188
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['cereals', 'spaghetti']),
                items_add=frozenset(['ground beef']),
                confidence=0.45999999999999996,
                lift=4.681763907734057
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'ground beef', 'chicken']),
        support=0.0038661511798426876,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['ground beef', 'chicken']),
                items_add=frozenset(['milk']),
                confidence=0.40845070422535207,
                lift=3.152046020981858
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['nan', 'light cream', 'chicken']),
        support=0.004532728969470737,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['light cream']),
                items_add=frozenset(['nan', 'chicken']),
                confidence=0.29059829059829057,
                lift=4.84395061728395
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['nan', 'light cream']),
                items_add=frozenset(['chicken']),
                confidence=0.29059829059829057,
                lift=4.84395061728395
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['olive oil', 'milk', 'chicken']),
        support=0.0035995200639914677,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['milk', 'chicken']),
                items_add=frozenset(['olive oil']),
                confidence=0.24324324324324323,
                lift=3.693456614509246
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['olive oil', 'chicken']),
                items_add=frozenset(['milk']),
                confidence=0.5,
                lift=3.858539094650206
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['milk', 'olive oil']),
                items_add=frozenset(['chicken']),
                confidence=0.2109375,
                lift=3.51609375
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['olive oil', 'spaghetti', 'chicken']),
        support=0.0034662045060658577,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['spaghetti', 'chicken']),
                items_add=frozenset(['olive oil']),
                confidence=0.20155038759689922,
                lift=3.0603835169318647
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['shrimp', 'chocolate', 'frozen vegetables']),
        support=0.005332622317024397,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['chocolate', 'frozen vegetables']),
                items_add=frozenset(['shrimp']),
                confidence=0.23255813953488375,
                lift=3.2545123221103784
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['shrimp', 'chocolate']),
                items_add=frozenset(['frozen vegetables']),
                confidence=0.29629629629629634,
                lift=3.1084175084175087
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['chocolate', 'ground beef', 'herb & pepper']),
        support=0.003999466737768298,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['chocolate', 'herb & pepper']),
                items_add=frozenset(['ground beef']),
                confidence=0.4411764705882354,
                lift=4.4901827759597746
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['chocolate', 'soup', 'milk']),
        support=0.003999466737768298,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['chocolate', 'soup']),
                items_add=frozenset(['milk']),
                confidence=0.3947368421052632,
                lift=3.0462150747238472
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['cooking oil', 'ground beef', 'spaghetti']),
        support=0.004799360085321957,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['cooking oil', 'ground beef']),
                items_add=frozenset(['spaghetti']),
                confidence=0.5714285714285714,
                lift=3.2819951870487856
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['cooking oil', 'spaghetti']),
                items_add=frozenset(['ground beef']),
                confidence=0.3025210084033613,
                lift=3.0789824749438446
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['eggs', 'ground beef', 'herb & pepper']),
        support=0.0041327822956939075,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['eggs', 'ground beef']),
                items_add=frozenset(['herb & pepper']),
                confidence=0.2066666666666667,
                lift=4.178454627133872
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['eggs', 'herb & pepper']),
                items_add=frozenset(['ground beef']),
                confidence=0.3297872340425532,
                lift=3.3564912381997174
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['eggs', 'spaghetti', 'red wine']),
        support=0.0037328356219170776,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['eggs', 'red wine']),
                items_add=frozenset(['spaghetti']),
                confidence=0.5283018867924528,
                lift=3.0342974370828397
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['escalope', 'mushroom cream sauce', 'nan']),
        support=0.005732568990801226,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['mushroom cream sauce']),
                items_add=frozenset(['escalope', 'nan']),
                confidence=0.3006993006993007,
                lift=3.790832696715049
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['nan', 'mushroom cream sauce']),
                items_add=frozenset(['escalope']),
                confidence=0.3006993006993007,
                lift=3.790832696715049
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['escalope', 'pasta', 'nan']),
        support=0.005865884548726837,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['pasta']),
                items_add=frozenset(['escalope', 'nan']),
                confidence=0.3728813559322034,
                lift=4.700811850163794
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['nan', 'pasta']),
                items_add=frozenset(['escalope']),
                confidence=0.3728813559322034,
                lift=4.700811850163794
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['french fries', 'ground beef', 'herb & pepper']),
        support=0.003199573390214638,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['french fries', 'ground beef']),
                items_add=frozenset(['herb & pepper']),
                confidence=0.23076923076923078,
                lift=4.665768194070081
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['french fries', 'herb & pepper']),
                items_add=frozenset(['ground beef']),
                confidence=0.46153846153846156,
                lift=4.697421981004071
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['nan', 'honey', 'fromage blanc']),
        support=0.003332888948140248,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['fromage blanc']),
                items_add=frozenset(['nan', 'honey']),
                confidence=0.2450980392156863,
                lift=5.1788180060756694
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['nan', 'fromage blanc']),
                items_add=frozenset(['honey']),
                confidence=0.2450980392156863,
                lift=5.164270764485569
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['frozen vegetables', 'tomatoes', 'green tea']),
        support=0.003332888948140248,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'green tea']),
                items_add=frozenset(['tomatoes']),
                confidence=0.2314814814814815,
                lift=3.38468341635983
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['frozen vegetables', 'spaghetti', 'ground beef']),
        support=0.008665511265164644,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'spaghetti']),
                items_add=frozenset(['ground beef']),
                confidence=0.31100478468899523,
                lift=3.165328208890303
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'frozen vegetables', 'olive oil']),
        support=0.004799360085321957,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['milk', 'frozen vegetables']),
                items_add=frozenset(['olive oil']),
                confidence=0.20338983050847456,
                lift=3.088314005352364
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'olive oil']),
                items_add=frozenset(['milk']),
                confidence=0.4235294117647058,
                lift=3.2684095860566447
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'frozen vegetables', 'soup']),
        support=0.003999466737768298,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'soup']),
                items_add=frozenset(['milk']),
                confidence=0.5,
                lift=3.858539094650206
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['milk', 'frozen vegetables', 'tomatoes']),
        support=0.0041327822956939075,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['milk', 'tomatoes']),
                items_add=frozenset(['frozen vegetables']),
                confidence=0.29523809523809524,
                lift=3.0973160173160172
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['shrimp', 'mineral water', 'frozen vegetables']),
        support=0.007199040127982935,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['shrimp', 'mineral water']),
                items_add=frozenset(['frozen vegetables']),
                confidence=0.30508474576271183,
                lift=3.200616332819722
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['frozen vegetables', 'spaghetti', 'olive oil']),
        support=0.005732568990801226,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'spaghetti']),
                items_add=frozenset(['olive oil']),
                confidence=0.20574162679425836,
                lift=3.1240241752707125
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['shrimp', 'frozen vegetables', 'spaghetti']),
        support=0.005999200106652446,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'spaghetti']),
                items_add=frozenset(['shrimp']),
                confidence=0.21531100478468898,
                lift=3.0131489680782684
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['shrimp', 'frozen vegetables', 'tomatoes']),
        support=0.003999466737768298,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['shrimp', 'frozen vegetables']),
                items_add=frozenset(['tomatoes']),
                confidence=0.24000000000000002,
                lift=3.5092397660818717
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['frozen vegetables', 'tomatoes']),
                items_add=frozenset(['shrimp']),
                confidence=0.2479338842975207,
                lift=3.4696866905143704
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['shrimp', 'tomatoes']),
                items_add=frozenset(['frozen vegetables']),
                confidence=0.35714285714285715,

In [85]:
resultados[0]

RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)])

In [86]:
resultados[0][0]

frozenset({'chicken', 'light cream'})

In [87]:
resultados[0][1]

0.004532728969470737

In [88]:
resultados[0][2]

[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]

In [89]:
resultados[0][2][0]

OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)

In [90]:
list(resultados[0][2])[0]

OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)

In [91]:
r = resultados[0][2]

In [92]:
r

[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]

In [93]:
r[0][0] # primeira regra "se"

frozenset({'light cream'})

In [94]:
r[0][1] # segunda regra "então"

frozenset({'chicken'})

In [95]:
r[0][2] # confiança

0.29059829059829057

In [96]:
r[0][3] # valores do lift

4.84395061728395

In [97]:
A = []
B = []
suporte = []
confianca = []
lift = []

for resultado in resultados:
  s = resultado[1]
  result_rules = resultado[2]
  for result_rule in result_rules:
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    A.append(a)
    B.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)

In [98]:
# ordenação e criar o dataframe

In [99]:
rules_df = pd.DataFrame({'A': A, 'B': B, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

In [100]:
rules_df.sort_values(by = 'lift', ascending = False).head(20)

,A,B,suporte,confianca,lift
344,"[frozen vegetables, soup]","[nan, mineral water, milk]",0.003066,0.383333,7.987176
177,"[frozen vegetables, soup]","[milk, mineral water]",0.003066,0.383333,7.987176
349,"[nan, frozen vegetables, soup]","[mineral water, milk]",0.003066,0.383333,7.987176
173,"[frozen vegetables, olive oil]","[milk, mineral water]",0.003333,0.294118,6.128268
339,"[nan, frozen vegetables, olive oil]","[mineral water, milk]",0.003333,0.294118,6.128268
336,"[frozen vegetables, olive oil]","[nan, mineral water, milk]",0.003333,0.294118,6.128268
268,"[mineral water, whole wheat pasta]","[nan, olive oil]",0.003866,0.402778,6.128268
269,"[nan, mineral water, whole wheat pasta]",[olive oil],0.003866,0.402778,6.115863
83,"[mineral water, whole wheat pasta]",[olive oil],0.003866,0.402778,6.115863
178,"[milk, soup]","[mineral water, frozen vegetables]",0.003066,0.201754,5.646864
351,"[nan, milk, soup]","[mineral water, frozen vegetables]",0.003066,0.201754,5.646864
345,"[milk, soup]","[nan, mineral water, frozen vegetables]",0.003066,0.201754,5.646864
239,[tomato sauce],"[nan, ground beef, spaghetti]",0.003066,0.216981,5.535971
241,"[nan, tomato sauce]","[ground beef, spaghetti]",0.003066,0.216981,5.535971
68,[tomato sauce],"[ground beef, spaghetti]",0.003066,0.216981,5.535971
352,"[nan, milk, frozen vegetables, mineral water]",[soup],0.003066,0.277108,5.484407
346,"[milk, frozen vegetables, mineral water]","[nan, soup]",0.003066,0.277108,5.484407
179,"[milk, frozen vegetables, mineral water]",[soup],0.003066,0.277108,5.484407
39,[fromage blanc],"[nan, honey]",0.003333,0.245098,5.178818
40,"[nan, fromage blanc]",[honey],0.003333,0.245098,5.164271

In [101]:
rules_df.sort_values(by = 'confianca', ascending = False).head(20)

,A,B,suporte,confianca,lift
347,"[milk, frozen vegetables, soup]","[nan, mineral water]",0.003066,0.766667,3.218112
353,"[nan, milk, frozen vegetables, soup]",[mineral water],0.003066,0.766667,3.216312
180,"[milk, frozen vegetables, soup]",[mineral water],0.003066,0.766667,3.216312
106,"[nan, ground beef, cereals]",[spaghetti],0.003066,0.676471,3.885303
104,"[ground beef, cereals]","[nan, spaghetti]",0.003066,0.676471,3.885303
15,"[ground beef, cereals]",[spaghetti],0.003066,0.676471,3.885303
89,"[tomatoes, olive oil]",[spaghetti],0.004399,0.611111,3.509912
274,"[nan, tomatoes, olive oil]",[spaghetti],0.004399,0.611111,3.509912
272,"[tomatoes, olive oil]","[nan, spaghetti]",0.004399,0.611111,3.509912
181,"[mineral water, frozen vegetables, soup]",[milk],0.003066,0.605263,4.670863
354,"[nan, mineral water, frozen vegetables, soup]",[milk],0.003066,0.605263,4.670863
348,"[mineral water, frozen vegetables, soup]","[nan, milk]",0.003066,0.605263,4.670863
243,"[nan, tomato sauce, ground beef]",[spaghetti],0.003066,0.575000,3.302508
240,"[tomato sauce, ground beef]","[nan, spaghetti]",0.003066,0.575000,3.302508
69,"[tomato sauce, ground beef]",[spaghetti],0.003066,0.575000,3.302508
143,"[cooking oil, ground beef, nan]",[spaghetti],0.004799,0.571429,3.281995
28,"[cooking oil, ground beef]",[spaghetti],0.004799,0.571429,3.281995
141,"[cooking oil, ground beef]","[nan, spaghetti]",0.004799,0.571429,3.281995
379,"[mineral water, ground beef, tomatoes]","[nan, spaghetti]",0.003066,0.560976,3.221959
233,"[mineral water, ground beef, tomatoes]",[spaghetti],0.003066,0.560976,3.221959

In [102]:
# lift  e confiança regra para empresa e verificar se há recompensa financeira.