## 30.4) Biblioteca PyOD => detecção de outliers

- Documentação: https://pyod.readthedocs.io/en/latest/#

(i) Individual Detection Algorithms :

Categoria	|	Algoritmos Famosos	|	Como funciona (Resumo)	|

Proximidade	|	kNN, LOF, COF	|	Medem a distância ou densidade local. Se um ponto está muito longe dos vizinhos ou em uma zona de baixa densidade, é um outlier.	|

Lineares	|	PCA, MCD, OCSVM	|	Usam projeções lineares. No PCA, por exemplo, outliers são pontos que não podem ser bem reconstruídos usando apenas os componentes principais.	|

Probabilísticos	|	ECOD, COPOD, GMM	|	Calculam a probabilidade de um ponto pertencer à distribuição dos dados. O ECOD é extremamente rápido e baseado em funções de distribuição acumulada.	|

Baseados em Árvores	|	Isolation Forest, LODA	|	O Isolation Forest "isola" as observações. Como outliers são raros e diferentes, eles são isolados com menos divisões na árvore do que pontos normais.	|

Redes Neurais	|	AutoEncoder, VAE, GAN	|	Tentam comprimir e reconstruir os dados. Outliers geralmente têm um erro de reconstrução muito alto.	|

- Neste exemplo usaremos o KNN, de proximidade

ambiente anaconda Udemy => erro no KNN ImportError: Numba needs NumPy 2.2 or less. Got NumPy 2.3.

ambiente anaconda orange3 => deu certo

In [10]:
#!pip install pyod

### importar o algoritmo de interesse

In [11]:
from pyod.models.knn import KNN

In [12]:
import numpy as np
print(np.__version__) # orange3

1.26.4

In [13]:
# versão udemy
#2.3.4

In [14]:
import pandas as pd
base_credit = pd.read_csv('credit_data.csv')
base_credit.tail()

      clientid        income        age         loan  default
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

In [15]:
base_credit.head(5)

   clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1

In [17]:
detector = KNN()

In [19]:
detector.get_params()

{'algorithm': 'auto',
 'contamination': 0.1,
 'leaf_size': 30,
 'method': 'largest',
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 5,
 'p': 2,
 'radius': 1.0}

contaminação base da distância

metric: Minkowski

 'p': 2, dstância euclidiana

In [21]:
base_credit.columns[1:4] # para ver o outliers serão essas colunas

Index(['income', 'age', 'loan'], dtype='object')

In [23]:
# Verifica a contagem de nulos em cada coluna
print(base_credit.iloc[:, 1:4].isnull().sum()) # deu erro no fit pois havia dados null

income    0
age       3
loan      0
dtype: int64

In [24]:
# Seleciona as colunas que você vai usar
X_credit = base_credit.iloc[:, 1:4]

# Preenche os nulos com a mediana de cada coluna
X_credit = X_credit.fillna(X_credit.median())

# Agora o fit deve funcionar normalmente
detector.fit(X_credit)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [25]:

# fit para fazer o treinamento
# calculo do treinamento com distância KNN
# os dados que tiverem as maiores distâncias serão considerados outliers
#detector.fit(base_credit.iloc[:,1:4]) #coletar todos os dados

In [26]:
detector.get_params()

{'algorithm': 'auto',
 'contamination': 0.1,
 'leaf_size': 30,
 'method': 'largest',
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 5,
 'p': 2,
 'radius': 1.0}

### 0 não é outliers e 1 é outliers

In [27]:
previsoes = detector.labels_
previsoes

array([0, 0, 0, ..., 0, 0, 1])


Esses são os hiperparâmetros do modelo KNN (K-Nearest Neighbors) do PyOD. Eles definem as "regras de negócio" que o algoritmo usará para decidir quem é um dado normal e quem é um outlier.

1. Os "Corações" do Modelo (Mais Importantes)
 
- contamination (0.1): É a porcentagem de outliers que você espera encontrar. 0.1 significa que o modelo vai marcar os 10% dos dados com as maiores distâncias como anomalias.

- n_neighbors (5): É o valor de $k$. O algoritmo olhará para os 5 vizinhos mais próximos de cada ponto para calcular o quão isolado ele está.

- method ('largest'): Define como o "score de anomalia" é calculado.

a) largest: Usa a distância até o 5º vizinho mais distante.

b) mean: Usa a média das distâncias de todos os 5 vizinhos.

- metric ('minkowski') e p (2): Definem a fórmula matemática da distância. Quando p=2, usando a Distância Euclidiana (a famosa linha reta entre dois pontos).

2. Configurações de Performance (Velocidade)
   
- algorithm ('auto'): O PyOD escolhe automaticamente a melhor estrutura de dados para buscar os vizinhos (como KDTree ou BallTree), dependendo do tamanho do seu dataset.

- leaf_size (30): É um parâmetro interno das árvores de busca (KDTree/BallTree). Afeta a velocidade da busca e o uso de memória, mas não o resultado final.

- n_jobs (1): Quantos núcleos do seu processador ele vai usar. 1 significa que ele usará apenas um núcleo. Para datasets gigantes, usar -1 aceleraria o processo usando todos os núcleos.

3. Parâmetros Específicos

- radius (1.0): Usado apenas se estivesse fazendo uma busca por raio em vez de número fixo de vizinhos (não é o caso aqui).

- metric_params (None): Serve para passar configurações extras para métricas de distância muito complexas ou personalizadas.

"Vou olhar para os 5 vizinhos mais próximos de cada registro usando a distância em linha reta. Se a distância até o 5º vizinho for muito grande (comparada aos outros), vou marcar esse registro como um dos 10% de outliers do meu banco de dados."

### contagens de quantos dados são de 0 ou 1

In [29]:
np.unique(previsoes, return_counts=True)

(array([0, 1]), array([1800,  200]))

In [ ]:
# valores sem ser outliers => 0

In [31]:
np.unique(previsoes, return_counts=True)[0][0]

0

In [34]:
print(f'Não é outliers {np.unique(previsoes, return_counts=True)[0][0]} e sua quantidade é de {np.unique(previsoes, return_counts=True)[1][0]}.')

Não é outliers 0 e sua quantidade é de 1800.

In [35]:
print(f'É outliers {np.unique(previsoes, return_counts=True)[0][1]} e sua quantidade é de {np.unique(previsoes, return_counts=True)[1][1]}.')

É outliers 1 e sua quantidade é de 200.

cálculo da distância com todos os atributos, diferentemente do gráfico do boxplot, ou do dispersão, os números de atributos são limitados, neste caso não.

Verificar a confiança dos dados

In [36]:
confianca_previsoes = detector.decision_scores_
confianca_previsoes

array([ 704.78948078,  365.218309  ,  583.2159934 , ...,  395.01466508,
        557.88978241, 1071.5109404 ])

confiança muito alta indica uma distância muito grande

In [41]:
previsoes[-4:] # últimos 4 dados

array([1, 0, 0, 1])

In [42]:
confianca_previsoes[-4:]

array([1015.87339884,  395.01466508,  557.88978241, 1071.5109404 ])

# verificar se é outliers ou não

In [46]:
outliers = []
for i in range(len(previsoes)):
  print(f'{i}) previsôes: {previsoes[i]} e confiança previsões: {confianca_previsoes[i]}')
  if previsoes[i] == 1:
    outliers.append(i)

0) previsôes: 0 e confiança previsões: 704.7894807791696
1) previsôes: 0 e confiança previsões: 365.21830899985906
2) previsôes: 0 e confiança previsões: 583.2159933969901
3) previsôes: 0 e confiança previsões: 669.1172307418985
4) previsôes: 1 e confiança previsões: 952.6002186476792
5) previsôes: 0 e confiança previsões: 546.2634915427162
6) previsôes: 0 e confiança previsões: 347.1669481891248
7) previsôes: 0 e confiança previsões: 573.3947097459896
8) previsôes: 0 e confiança previsões: 532.7286552405403
9) previsôes: 0 e confiança previsões: 561.8260615496696
10) previsôes: 0 e confiança previsões: 611.0671075771143
11) previsôes: 0 e confiança previsões: 645.8081658751695
12) previsôes: 0 e confiança previsões: 540.9591139816707
13) previsôes: 0 e confiança previsões: 611.5593802198417
14) previsôes: 0 e confiança previsões: 814.334639739793
15) previsôes: 0 e confiança previsões: 723.1341876580393
16) previsôes: 0 e confiança previsões: 679.8718686007359
17) previsôes: 0 e confiança previsões: 679.8718686007359
18) previsôes: 0 e confiança previsões: 371.1955496485334
19) previsôes: 0 e confiança previsões: 461.27271215226193
20) previsôes: 0 e confiança previsões: 448.3874684758544
21) previsôes: 0 e confiança previsões: 428.2939936630485
22) previsôes: 0 e confiança previsões: 386.4346631719257
23) previsôes: 0 e confiança previsões: 611.5593802198417
24) previsôes: 1 e confiança previsões: 1033.6236316807965
25) previsôes: 0 e confiança previsões: 651.7409680384661
26) previsôes: 0 e confiança previsões: 818.3705671073396
27) previsôes: 0 e confiança previsões: 583.9032936325012
28) previsôes: 0 e confiança previsões: 548.6967881039217
29) previsôes: 1 e confiança previsões: 987.6621062742156
30) previsôes: 0 e confiança previsões: 310.571884508124
31) previsôes: 0 e confiança previsões: 402.38252062522355
32) previsôes: 0 e confiança previsões: 577.454142099822
33) previsôes: 0 e confiança previsões: 778.3102585188749
34) previsôes: 1 e confiança previsões: 862.441613115992
35) previsôes: 0 e confiança previsões: 622.9443058262689
36) previsôes: 0 e confiança previsões: 343.91343300648685
37) previsôes: 0 e confiança previsões: 432.75026373546865
38) previsôes: 1 e confiança previsões: 827.8685600824664
39) previsôes: 0 e confiança previsões: 530.3897292567402
40) previsôes: 0 e confiança previsões: 804.8344282890544
41) previsôes: 0 e confiança previsões: 511.82989560327013
42) previsôes: 0 e confiança previsões: 758.0296694325052
43) previsôes: 0 e confiança previsões: 486.2346970131449
44) previsôes: 0 e confiança previsões: 703.7020425494393
45) previsôes: 0 e confiança previsões: 466.05376134777225
46) previsôes: 0 e confiança previsões: 642.624552441227
47) previsôes: 0 e confiança previsões: 393.8621675197818
48) previsôes: 0 e confiança previsões: 359.2704292991963
49) previsôes: 0 e confiança previsões: 567.7459443553499
50) previsôes: 0 e confiança previsões: 487.238549008794
51) previsôes: 0 e confiança previsões: 600.5843183314386
52) previsôes: 0 e confiança previsões: 506.23190888480076
53) previsôes: 0 e confiança previsões: 625.5922634672114
54) previsôes: 0 e confiança previsões: 410.91872871064544
55) previsôes: 0 e confiança previsões: 625.2729062032814
56) previsôes: 0 e confiança previsões: 287.3279303722045
57) previsôes: 0 e confiança previsões: 422.87004692762116
58) previsôes: 0 e confiança previsões: 667.0472380721922
59) previsôes: 0 e confiança previsões: 652.874326716956
60) previsôes: 0 e confiança previsões: 507.9622135762928
61) previsôes: 0 e confiança previsões: 592.5601907116727
62) previsôes: 0 e confiança previsões: 569.2096079488323
63) previsôes: 0 e confiança previsões: 528.3914437387713
64) previsôes: 0 e confiança previsões: 759.7717829473717
65) previsôes: 0 e confiança previsões: 440.87846448994327
66) previsôes: 0 e confiança previsões: 782.1993333044549
67) previsôes: 0 e confiança previsões: 485.44611777323246
68) previsôes: 0 e confiança previsões: 332.9910088009004
69) previsôes: 0 e confiança previsões: 470.0864573023725
70) previsôes: 0 e confiança previsões: 635.0606364607702
71) previsôes: 0 e confiança previsões: 557.9365862514221
72) previsôes: 0 e confiança previsões: 501.62303253155557
73) previsôes: 0 e confiança previsões: 600.5843183314386
74) previsôes: 0 e confiança previsões: 464.8716529367167
75) previsôes: 0 e confiança previsões: 680.0910914343377
76) previsôes: 0 e confiança previsões: 472.1413668671309
77) previsôes: 0 e confiança previsões: 529.8655529453948
78) previsôes: 1 e confiança previsões: 848.0899460561573
79) previsôes: 0 e confiança previsões: 639.0002826106794
80) previsôes: 0 e confiança previsões: 480.2359935236739
81) previsôes: 0 e confiança previsões: 628.0387698699392
82) previsôes: 0 e confiança previsões: 659.220664020664
83) previsôes: 0 e confiança previsões: 702.2805825204139
84) previsôes: 0 e confiança previsões: 322.0932482380197
85) previsôes: 0 e confiança previsões: 790.4712568521039
86) previsôes: 0 e confiança previsões: 576.3456074383455
87) previsôes: 0 e confiança previsões: 455.79185102918524
88) previsôes: 0 e confiança previsões: 439.43435385329457
89) previsôes: 0 e confiança previsões: 621.7665625334157
90) previsôes: 1 e confiança previsões: 958.7599990359109
91) previsôes: 0 e confiança previsões: 363.09229574170274
92) previsôes: 0 e confiança previsões: 385.64854485226584
93) previsôes: 0 e confiança previsões: 250.24953588303504
94) previsôes: 0 e confiança previsões: 436.1356356195144
95) previsôes: 1 e confiança previsões: 852.932101479946
96) previsôes: 0 e confiança previsões: 419.456975076895
97) previsôes: 0 e confiança previsões: 472.7353366270208
98) previsôes: 0 e confiança previsões: 719.0746036227307
99) previsôes: 0 e confiança previsões: 382.5277556362385
100) previsôes: 0 e confiança previsões: 734.1066586537637
101) previsôes: 0 e confiança previsões: 585.1385258871375
102) previsôes: 0 e confiança previsões: 711.1490830352166
103) previsôes: 0 e confiança previsões: 550.6031580905776
104) previsôes: 1 e confiança previsões: 1277.8720509655511
105) previsôes: 1 e confiança previsões: 1189.7221566694966
106) previsôes: 0 e confiança previsões: 465.37764059794165
107) previsôes: 0 e confiança previsões: 525.2151212304174
108) previsôes: 0 e confiança previsões: 552.1197190707375
109) previsôes: 0 e confiança previsões: 411.5935061390086
110) previsôes: 0 e confiança previsões: 508.3913522852474
111) previsôes: 1 e confiança previsões: 1043.0728690685253
112) previsôes: 0 e confiança previsões: 513.0469923176672
113) previsôes: 0 e confiança previsões: 557.9614499092064
114) previsôes: 0 e confiança previsões: 510.59339892355814
115) previsôes: 1 e confiança previsões: 944.0232696583748
116) previsôes: 0 e confiança previsões: 674.8421792755896
117) previsôes: 0 e confiança previsões: 473.2354481199715
118) previsôes: 0 e confiança previsões: 453.3556796520386
119) previsôes: 0 e confiança previsões: 441.22477845862875
120) previsôes: 0 e confiança previsões: 704.0630208811767
121) previsôes: 0 e confiança previsões: 547.8888752598502
122) previsôes: 0 e confiança previsões: 365.9055894074661
123) previsôes: 0 e confiança previsões: 631.4890533148454
124) previsôes: 0 e confiança previsões: 632.6336416311091
125) previsôes: 0 e confiança previsões: 606.0020020790901
126) previsôes: 0 e confiança previsões: 385.95056894564885
127) previsôes: 0 e confiança previsões: 539.4190186204916
128) previsôes: 1 e confiança previsões: 932.9394204283942
129) previsôes: 0 e confiança previsões: 516.5997350504471
130) previsôes: 0 e confiança previsões: 724.4249154825159
131) previsôes: 0 e confiança previsões: 698.4901412535303
132) previsôes: 0 e confiança previsões: 436.6724755873861
133) previsôes: 0 e confiança previsões: 527.4992759890824
134) previsôes: 0 e confiança previsões: 413.37043948368455
135) previsôes: 0 e confiança previsões: 527.4392406435181
136) previsôes: 0 e confiança previsões: 527.0026536625259
137) previsôes: 0 e confiança previsões: 439.53493790853923
138) previsôes: 0 e confiança previsões: 685.0054828452207
139) previsôes: 0 e confiança previsões: 556.0417343466977
140) previsôes: 0 e confiança previsões: 773.8130264597846
141) previsôes: 0 e confiança previsões: 573.571028739244
142) previsôes: 0 e confiança previsões: 364.4549210307659
143) previsôes: 0 e confiança previsões: 576.1140085100707
144) previsôes: 0 e confiança previsões: 683.3438622950437
145) previsôes: 0 e confiança previsões: 659.220664020664
146) previsôes: 0 e confiança previsões: 442.17403965062647
147) previsôes: 0 e confiança previsões: 499.88974005456015
148) previsôes: 0 e confiança previsões: 765.5084338324817
149) previsôes: 0 e confiança previsões: 415.4059938357863
150) previsôes: 0 e confiança previsões: 675.5954196376687
151) previsôes: 0 e confiança previsões: 611.5259806255797
152) previsôes: 0 e confiança previsões: 435.6664740426257
153) previsôes: 0 e confiança previsões: 429.66737804737113
154) previsôes: 0 e confiança previsões: 363.3691061762681
155) previsôes: 0 e confiança previsões: 677.7209909338192
156) previsôes: 0 e confiança previsões: 755.5058000694872
157) previsôes: 1 e confiança previsões: 939.1267225731907
158) previsôes: 0 e confiança previsões: 552.0095724496105
159) previsôes: 0 e confiança previsões: 511.8637550406715
160) previsôes: 1 e confiança previsões: 864.9542388103566
161) previsôes: 0 e confiança previsões: 510.395713430851
162) previsôes: 0 e confiança previsões: 626.1170371601686
163) previsôes: 1 e confiança previsões: 883.1553905265798
164) previsôes: 0 e confiança previsões: 598.7375746037893
165) previsôes: 1 e confiança previsões: 1055.2052594414342
166) previsôes: 0 e confiança previsões: 442.2875737359182
167) previsôes: 0 e confiança previsões: 422.2499395932415
168) previsôes: 0 e confiança previsões: 444.5172297683205
169) previsôes: 0 e confiança previsões: 367.3546188467006
170) previsôes: 0 e confiança previsões: 514.9485296392925
171) previsôes: 0 e confiança previsões: 473.8795233738517
172) previsôes: 0 e confiança previsões: 369.17716523568754
173) previsôes: 0 e confiança previsões: 430.27423299157886
174) previsôes: 0 e confiança previsões: 560.3189778047416
175) previsôes: 0 e confiança previsões: 518.3387622113303
176) previsôes: 0 e confiança previsões: 329.55233678866057
177) previsôes: 0 e confiança previsões: 803.5317658573327
178) previsôes: 0 e confiança previsões: 608.9388232406377
179) previsôes: 0 e confiança previsões: 513.9059383745664
180) previsôes: 0 e confiança previsões: 440.25826967877254
181) previsôes: 0 e confiança previsões: 687.7613842862235
182) previsôes: 0 e confiança previsões: 364.7963377882755
183) previsôes: 0 e confiança previsões: 488.1918285921261
184) previsôes: 0 e confiança previsões: 537.7057332488148
185) previsôes: 0 e confiança previsões: 694.4706581232688
186) previsôes: 1 e confiança previsões: 866.1227506571465
187) previsôes: 0 e confiança previsões: 530.175598287646
188) previsôes: 0 e confiança previsões: 484.4044283594847
189) previsôes: 0 e confiança previsões: 698.8604695884918
190) previsôes: 0 e confiança previsões: 393.39024493630217
191) previsôes: 0 e confiança previsões: 584.1282158008612
192) previsôes: 0 e confiança previsões: 381.54212082346726
193) previsôes: 0 e confiança previsões: 527.2600850508034
194) previsôes: 0 e confiança previsões: 533.9718711129264
195) previsôes: 0 e confiança previsões: 581.1237354254494
196) previsôes: 0 e confiança previsões: 599.7669110858745
197) previsôes: 0 e confiança previsões: 488.9637462917475
198) previsôes: 0 e confiança previsões: 357.5613339632897
199) previsôes: 0 e confiança previsões: 792.3303618164366
200) previsôes: 0 e confiança previsões: 701.5019692591434
201) previsôes: 0 e confiança previsões: 578.5929886354736
202) previsôes: 0 e confiança previsões: 649.0360106286043
203) previsôes: 0 e confiança previsões: 443.1852527178513
204) previsôes: 0 e confiança previsões: 367.63899782815827
205) previsôes: 0 e confiança previsões: 400.002888001695
206) previsôes: 0 e confiança previsões: 701.462808321599
207) previsôes: 0 e confiança previsões: 745.8763274689126
208) previsôes: 0 e confiança previsões: 647.0629798252581
209) previsôes: 0 e confiança previsões: 628.991583050537
210) previsôes: 0 e confiança previsões: 421.89606357006375
211) previsôes: 0 e confiança previsões: 339.84690372658247
212) previsôes: 0 e confiança previsões: 545.009489116423
213) previsôes: 0 e confiança previsões: 554.5140343724312
214) previsôes: 0 e confiança previsões: 613.5611223839929
215) previsôes: 0 e confiança previsões: 647.4354279622308
216) previsôes: 0 e confiança previsões: 512.4486001266283
217) previsôes: 0 e confiança previsões: 712.2692151461872
218) previsôes: 1 e confiança previsões: 892.9408218593248
219) previsôes: 0 e confiança previsões: 308.38850239373323
220) previsôes: 1 e confiança previsões: 891.8375948547426
221) previsôes: 0 e confiança previsões: 613.7027545017212
222) previsôes: 0 e confiança previsões: 525.2063948621499
223) previsôes: 0 e confiança previsões: 740.5452351897649
224) previsôes: 0 e confiança previsões: 521.1777694856657
225) previsôes: 0 e confiança previsões: 614.2245645212112
226) previsôes: 0 e confiança previsões: 630.6076937536587
227) previsôes: 0 e confiança previsões: 536.6696629786715
228) previsôes: 0 e confiança previsões: 735.7292304626746
229) previsôes: 0 e confiança previsões: 721.9193176795426
230) previsôes: 0 e confiança previsões: 569.3670963286922
231) previsôes: 0 e confiança previsões: 409.41839110807183
232) previsôes: 0 e confiança previsões: 582.5161642200733
233) previsôes: 0 e confiança previsões: 473.72858259553004
234) previsôes: 1 e confiança previsões: 920.8073216026
235) previsôes: 0 e confiança previsões: 701.216263656416
236) previsôes: 0 e confiança previsões: 502.09612181109765
237) previsôes: 1 e confiança previsões: 936.1652214341585
238) previsôes: 0 e confiança previsões: 705.4805274350646
239) previsôes: 0 e confiança previsões: 413.85193929164046
240) previsôes: 0 e confiança previsões: 604.4243433264714
241) previsôes: 0 e confiança previsões: 434.4429623014817
242) previsôes: 0 e confiança previsões: 546.4690073294022
243) previsôes: 0 e confiança previsões: 421.3639128386822
244) previsôes: 0 e confiança previsões: 448.0381609999888
245) previsôes: 0 e confiança previsões: 458.0465293001251
246) previsôes: 0 e confiança previsões: 639.0423877285801
247) previsôes: 0 e confiança previsões: 708.3950539445373
248) previsôes: 0 e confiança previsões: 479.0800087491928
249) previsôes: 0 e confiança previsões: 412.2686921237152
250) previsôes: 0 e confiança previsões: 436.3333313546366
251) previsôes: 0 e confiança previsões: 419.51205885109727
252) previsôes: 0 e confiança previsões: 527.9403608260438
253) previsôes: 0 e confiança previsões: 408.5355226215189
254) previsôes: 0 e confiança previsões: 732.238936096037
255) previsôes: 0 e confiança previsões: 409.22730943779356
256) previsôes: 0 e confiança previsões: 493.8495645567627
257) previsôes: 0 e confiança previsões: 663.1211603199423
258) previsôes: 0 e confiança previsões: 602.9873848818298
259) previsôes: 0 e confiança previsões: 562.5906001745773
260) previsôes: 0 e confiança previsões: 489.5306365793171
261) previsôes: 0 e confiança previsões: 534.7371588996941
262) previsôes: 0 e confiança previsões: 683.0008137868564
263) previsôes: 0 e confiança previsões: 714.9873797890112
264) previsôes: 0 e confiança previsões: 717.8535921887305
265) previsôes: 0 e confiança previsões: 383.91840851055747
266) previsôes: 0 e confiança previsões: 524.9989378749705
267) previsôes: 0 e confiança previsões: 590.3511955906534
268) previsôes: 0 e confiança previsões: 627.1856366429188
269) previsôes: 0 e confiança previsões: 488.1778469795397
270) previsôes: 0 e confiança previsões: 649.9521144136606
271) previsôes: 0 e confiança previsões: 523.8617496102224
272) previsôes: 0 e confiança previsões: 507.9622135762928
273) previsôes: 0 e confiança previsões: 542.2587138609808
274) previsôes: 0 e confiança previsões: 546.3061725262398
275) previsôes: 1 e confiança previsões: 1138.3399046756938
276) previsôes: 0 e confiança previsões: 404.43179318011136
277) previsôes: 0 e confiança previsões: 578.6952336861349
278) previsôes: 0 e confiança previsões: 451.3180877703957
279) previsôes: 0 e confiança previsões: 232.57672404156747
280) previsôes: 0 e confiança previsões: 535.754972473928
281) previsôes: 0 e confiança previsões: 387.63938953855074
282) previsôes: 1 e confiança previsões: 831.7781583964792
283) previsôes: 0 e confiança previsões: 574.0553283833734
284) previsôes: 0 e confiança previsões: 639.5777770473168
285) previsôes: 0 e confiança previsões: 592.3599535536101
286) previsôes: 0 e confiança previsões: 668.8594008302568
287) previsôes: 0 e confiança previsões: 649.0360106286043
288) previsôes: 0 e confiança previsões: 673.1860061369216
289) previsôes: 0 e confiança previsões: 257.2604492154735
290) previsôes: 0 e confiança previsões: 667.3955996002968
291) previsôes: 0 e confiança previsões: 639.4797464235355
292) previsôes: 1 e confiança previsões: 831.1099033258273
293) previsôes: 0 e confiança previsões: 589.5933953525741
294) previsôes: 0 e confiança previsões: 427.3185579884859
295) previsôes: 0 e confiança previsões: 690.6537197311393
296) previsôes: 0 e confiança previsões: 665.4578889167751
297) previsôes: 1 e confiança previsões: 901.2548802514832
298) previsôes: 0 e confiança previsões: 501.5723164995772
299) previsôes: 0 e confiança previsões: 441.7682005856819
300) previsôes: 0 e confiança previsões: 373.0420585697046
301) previsôes: 0 e confiança previsões: 371.3393599037023
302) previsôes: 0 e confiança previsões: 483.40888953206166
303) previsôes: 0 e confiança previsões: 460.7983973815728
304) previsôes: 1 e confiança previsões: 836.7207526069631
305) previsôes: 0 e confiança previsões: 778.3198412586536
306) previsôes: 0 e confiança previsões: 452.35549434297366
307) previsôes: 0 e confiança previsões: 475.79690409242085
308) previsôes: 0 e confiança previsões: 457.3763308353569
309) previsôes: 0 e confiança previsões: 364.72170376500236
310) previsôes: 0 e confiança previsões: 710.7290981190615
311) previsôes: 0 e confiança previsões: 363.63462638473777
312) previsôes: 0 e confiança previsões: 728.2461431715875
313) previsôes: 0 e confiança previsões: 436.91934006023695
314) previsôes: 0 e confiança previsões: 581.018465181943
315) previsôes: 0 e confiança previsões: 448.1725952423607
316) previsôes: 0 e confiança previsões: 411.2245258183959
317) previsôes: 0 e confiança previsões: 647.3053879377993
318) previsôes: 0 e confiança previsões: 703.2158471434609
319) previsôes: 0 e confiança previsões: 608.2427289706981
320) previsôes: 0 e confiança previsões: 438.2008539188414
321) previsôes: 0 e confiança previsões: 514.7687493457479
322) previsôes: 0 e confiança previsões: 627.6730161310334
323) previsôes: 0 e confiança previsões: 680.963925519843
324) previsôes: 1 e confiança previsões: 841.7162094298956
325) previsôes: 1 e confiança previsões: 1403.3107828684622
326) previsôes: 0 e confiança previsões: 636.0099791536531
327) previsôes: 0 e confiança previsões: 503.80414318781754
328) previsôes: 0 e confiança previsões: 561.1513880638882
329) previsôes: 0 e confiança previsões: 681.6431210494804
330) previsôes: 0 e confiança previsões: 546.8203297658918
331) previsôes: 0 e confiança previsões: 383.2389792530473
332) previsôes: 0 e confiança previsões: 477.95980264813977
333) previsôes: 0 e confiança previsões: 417.05884573858054
334) previsôes: 0 e confiança previsões: 550.7149947782082
335) previsôes: 1 e confiança previsões: 965.9174996942983
336) previsôes: 0 e confiança previsões: 675.1055908648544
337) previsôes: 0 e confiança previsões: 410.91872871064544
338) previsôes: 0 e confiança previsões: 659.2254093530717
339) previsôes: 0 e confiança previsões: 818.2161164018911

In [47]:
outliers

[4,
 24,
 29,
 34,
 38,
 78,
 90,
 95,
 104,
 105,
 111,
 115,
 128,
 157,
 160,
 163,
 165,
 186,
 218,
 220,
 234,
 237,
 275,
 282,
 292,
 297,
 304,
 324,
 325,
 335,
 342,
 346,
 350,
 360,
 361,
 394,
 402,
 404,
 405,
 414,
 421,
 422,
 427,
 449,
 450,
 452,
 454,
 480,
 488,
 489,
 505,
 508,
 523,
 531,
 533,
 535,
 548,
 573,
 599,
 633,
 646,
 663,
 697,
 710,
 716,
 737,
 748,
 765,
 767,
 842,
 851,
 869,
 878,
 880,
 885,
 898,
 901,
 927,
 930,
 933,
 940,
 945,
 946,
 952,
 975,
 977,
 990,
 992,
 996,
 999,
 1002,
 1006,
 1018,
 1025,
 1028,
 1034,
 1036,
 1040,
 1041,
 1050,
 1057,
 1065,
 1083,
 1088,
 1091,
 1092,
 1094,
 1101,
 1102,
 1128,
 1139,
 1140,
 1184,
 1197,
 1200,
 1202,
 1208,
 1210,
 1212,
 1219,
 1222,
 1235,
 1236,
 1239,
 1291,
 1292,
 1303,
 1338,
 1350,
 1351,
 1370,
 1377,
 1378,
 1379,
 1382,
 1385,
 1388,
 1389,
 1396,
 1414,
 1415,
 1417,
 1428,
 1429,
 1435,
 1443,
 1448,
 1454,
 1470,
 1481,
 1492,
 1506,
 1514,
 1516,
 1520,
 1566,
 1582,
 1584,
 1608,
 1610,
 1616,
 1618,
 1626,
 1630,
 1635,
 1648,
 1660,
 1668,
 1672,
 1675,
 1679,
 1681,
 1694,
 1705,
 1716,
 1720,
 1727,
 1733,
 1739,
 1752,
 1755,
 1787,
 1801,
 1803,
 1815,
 1819,
 1824,
 1830,
 1834,
 1902,
 1913,
 1914,
 1915,
 1930,
 1935,
 1943,
 1944,
 1957,
 1996,
 1999]

In [48]:
print('lista dos ids que são outliers')
print(outliers)

lista dos ids que são outliers
[4, 24, 29, 34, 38, 78, 90, 95, 104, 105, 111, 115, 128, 157, 160, 163, 165, 186, 218, 220, 234, 237, 275, 282, 292, 297, 304, 324, 325, 335, 342, 346, 350, 360, 361, 394, 402, 404, 405, 414, 421, 422, 427, 449, 450, 452, 454, 480, 488, 489, 505, 508, 523, 531, 533, 535, 548, 573, 599, 633, 646, 663, 697, 710, 716, 737, 748, 765, 767, 842, 851, 869, 878, 880, 885, 898, 901, 927, 930, 933, 940, 945, 946, 952, 975, 977, 990, 992, 996, 999, 1002, 1006, 1018, 1025, 1028, 1034, 1036, 1040, 1041, 1050, 1057, 1065, 1083, 1088, 1091, 1092, 1094, 1101, 1102, 1128, 1139, 1140, 1184, 1197, 1200, 1202, 1208, 1210, 1212, 1219, 1222, 1235, 1236, 1239, 1291, 1292, 1303, 1338, 1350, 1351, 1370, 1377, 1378, 1379, 1382, 1385, 1388, 1389, 1396, 1414, 1415, 1417, 1428, 1429, 1435, 1443, 1448, 1454, 1470, 1481, 1492, 1506, 1514, 1516, 1520, 1566, 1582, 1584, 1608, 1610, 1616, 1618, 1626, 1630, 1635, 1648, 1660, 1668, 1672, 1675, 1679, 1681, 1694, 1705, 1716, 1720, 1727, 1733, 1739, 1752, 1755, 1787, 1801, 1803, 1815, 1819, 1824, 1830, 1834, 1902, 1913, 1914, 1915, 1930, 1935, 1943, 1944, 1957, 1996, 1999]

Registro completo dos clientes

In [49]:
#[:,:] # : todos os registros
# [outliers,:] indicar qual ids selecionados que são outliers
lista_outliers = base_credit.iloc[outliers,:]
lista_outliers

      clientid        income        age          loan  default
4            5  66952.688845  18.584336   8770.099235        1
24          25  65301.984029  48.840922   5465.267886        0
29          30  58842.891308  54.510948  10871.186790        0
34          35  57584.973790  36.672021   1728.423755        0
38          39  60921.063104  18.840526    968.836383        0
...        ...           ...        ...           ...      ...
1943      1944  59792.508585  24.187499    660.241453        0
1944      1945  35879.519994  41.072935   5335.403499        0
1957      1958  50458.958203  52.314565   9852.889427        0
1996      1997  69516.127573  23.162104   3503.176156        0
1999      2000  69436.579552  56.152617   7378.833599        0

[200 rows x 5 columns]

In [50]:
# lista completa e salvar para a detecção de fraude
lista_outliers.tail(10)

      clientid        income        age          loan  default
1913      1914  69992.332712  41.771231     52.872190        0
1914      1915  68110.239953  32.171575  11029.667710        1
1915      1916  48015.554743  28.241796     54.008242        0
1930      1931  44241.283000  19.982539   8733.179295        1
1935      1936  33707.801036  59.917644    321.578931        0
1943      1944  59792.508585  24.187499    660.241453        0
1944      1945  35879.519994  41.072935   5335.403499        0
1957      1958  50458.958203  52.314565   9852.889427        0
1996      1997  69516.127573  23.162104   3503.176156        0
1999      2000  69436.579552  56.152617   7378.833599        0