In [1]:
#$conda env list
# conda environments:

#
#base                  *  /home/fabiene/anaconda3
#Maq2                     /home/fabiene/anaconda3/envs/Maq2
#RBA_est                  /home/fabiene/anaconda3/envs/RBA_est
#Robyn                    /home/fabiene/anaconda3/envs/Robyn
#Udemy                    /home/fabiene/anaconda3/envs/Udemy
#YouTube                  /home/fabiene/anaconda3/envs/YouTube
#pycaret-env              /home/fabiene/anaconda3/envs/pycaret-env

#$ conda activate YouTube

Arquivo pesquisa

https://www.kaggle.com/datasets/toramky/automobile-dataset?resource=download

https://medium.com/@jair.oliveira1204/an%C3%A1lise-explorat%C3%B3ria-de-dados-com-pandas-profiling-8c2edeeb6958

características de automóveis.


Profiling é ideal antes de fazermos qualquer tratativa dos dados, pois, assim teremos uma visão interresante e extrair insights importantes para uma análise mais específica.

In [2]:
# Import das bibliotecas
import pandas as pd
import numpy as np
# Carregando os dados
data = pd.read_csv('Automobile_data.csv')
data.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [3]:
data.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

https://docs.profiling.ydata.ai/latest/

In [8]:
#!pip install pandas-profiling
#!pip install numba==0.55.2
#!pip uninstall pandas-profiling
#!pip install pandas-profiling
#pip install numba

# correto o programa atualizado
#!pip install ydata-profiling

In [10]:
from ydata_profiling import ProfileReport

profile = ProfileReport(
    data,
    title='Automobile data',
    html={'style': {'full_width': True}},
    sort=None  # CORRETO: sem aspas
)

profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 26/26 [00:00<00:00, 101443.63it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
# antigo
#from pandas_profiling import ProfileReport

#profile = ProfileReport(data, title='Automobile data',
                 html={'style': {'full_width': True}}, sort="None")
#profile

IndentationError: unexpected indent (673094924.py, line 5)

In [12]:
# relatório criado
profile.to_file("relatorio.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]