# 18.9) Preço das Casas

# Regressão com Random Forest

In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import pandas as pd
base_casas = pd.read_csv('../13-Regressao/house_prices.csv')
base_casas.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [3]:
base_casas.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [4]:
# data da publicação do preço (date)
# price - preço
# sqft_living - metragem quadrada do local, casa apt. (sua atualização - sqft_living15)
# sqft_lot - metragem quadrada do lote.  (sua atualização - sqft_lot15)
# floors - quantidade dos andares.
# condition- condição da casa.
# grade - nota da casa.
# yr_built - ano construida.
# yr_renovated - ano renovada.
# zipcode - cep.

In [5]:
base_casas.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

Primeiro quartil 25% da base de dados.

Terceiro Quartil 75% da base de dados.

Segundo Quartil 50% da base de dados. -> ou a mediana.

mean - média

Verificar atributos faltantes

In [6]:
list(base_casas.columns)

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [7]:
list(base_casas.columns)[3:19] # coletar os dados até a longitude, começando dos quartos.

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [8]:
len(list(base_casas.columns)[3:19]) #quantidade de colunas do x

16

In [9]:
# selecionar todas as linhas [:,
# selecionar as colundas da 3 à 19 iloc[:, 3:19]
# atributos abaixo selecionados.
X_casas = base_casas.iloc[:, 3:19].values
X_casas

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [10]:
list(base_casas.columns)[2] # coletar o dado de y, no caso a previsão do preço

'price'

In [11]:
y_casas = base_casas.iloc[:, 2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [12]:
# vamos prever os preços, para isso vamos separar bases dos treinos.

from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(X_casas, y_casas, test_size = 0.3, random_state = 0)

## Base preço das casas

In [13]:
X_casas_treinamento.shape

(15129, 16)

In [14]:
X_casas_treinamento

array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
         4.77224e+01, -1.22332e+02],
       [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
         4.77725e+01, -1.22349e+02],
       [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
         4.77082e+01, -1.22104e+02],
       ...,
       [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
         4.73856e+01, -1.22158e+02],
       [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
         4.72831e+01, -1.22279e+02],
       [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
         4.76126e+01, -1.22120e+02]])

In [15]:
y_casas_treinamento  # preço real das casas

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [16]:
X_casas_teste # conjunto de registros para o teste.

array([[ 2.00000e+00,  1.50000e+00,  1.43000e+03, ...,  9.81250e+04,
         4.77222e+01, -1.22290e+02],
       [ 4.00000e+00,  3.25000e+00,  4.67000e+03, ...,  9.80050e+04,
         4.76350e+01, -1.22164e+02],
       [ 2.00000e+00,  7.50000e-01,  1.44000e+03, ...,  9.81070e+04,
         4.76707e+01, -1.22364e+02],
       ...,
       [ 3.00000e+00,  2.50000e+00,  2.15000e+03, ...,  9.80580e+04,
         4.74514e+01, -1.22089e+02],
       [ 3.00000e+00,  1.75000e+00,  1.48000e+03, ...,  9.80320e+04,
         4.73657e+01, -1.22280e+02],
       [ 3.00000e+00,  1.00000e+00,  1.32000e+03, ...,  9.80920e+04,
         4.73120e+01, -1.22183e+02]])

In [17]:
# import o random forest
from sklearn.ensemble import RandomForestRegressor

In [18]:
# será incluido 100 árvores de decisão(n_estimators), por conta da base de dados grande.
regressor_random_forest_casas = RandomForestRegressor(n_estimators=100)
# treinar o modelo
regressor_random_forest_casas.fit(X_casas_treinamento, y_casas_treinamento)

RandomForestRegressor()

In [19]:
regressor_random_forest_casas.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [20]:
regressor_random_forest_casas.score(X_casas_treinamento, y_casas_treinamento)

0.9808951530300564

In [21]:
qualidade_algoritmo_treino = regressor_random_forest_casas.score(X_casas_treinamento, y_casas_treinamento)

print('A acurácia do modelo Random Forest com regressão é de {:.0f}% no Preço das Casas para treino.'.format(qualidade_algoritmo_treino*100)) 
# quanto mais perto de 1, melhor é esse valor.

A acurácia do modelo Random Forest com regressão é de 98% no Preço das Casas para treino.

In [22]:
regressor_random_forest_casas.score(X_casas_teste, y_casas_teste)

0.8811886560336709

In [23]:
qualidade_algoritmo_teste = regressor_random_forest_casas.score(X_casas_teste, y_casas_teste)


print('A acurácia do modelo Random Forest com regressão é de {:.0f}% no Preço das Casas para teste.'.format(qualidade_algoritmo_teste*100)) 
# quanto mais perto de 1, melhor é esse valor.

A acurácia do modelo Random Forest com regressão é de 88% no Preço das Casas para teste.

In [25]:
#BASE PREÇO DAS CASAS

#Acurácia na regressão linear simples de: 49.5% e 48.9% treino e teste
#Acurácia na regressão linear múltipla de: 70 e 68% treino e teste
#Acurácia na regressão linear Polinomial de: 79,2% a 79,5% treino e teste
#Acurácia na regressão linear Com árvore de decisão: 99,9% e 70,3% treino e teste
#Acurácia na regressão linear Com random forest: 98% e 88% treino e teste => pelo teste este é o melhor modelo

# fazendo a previsão dos preços das casas

In [26]:
previsoes = regressor_random_forest_casas.predict(X_casas_teste)
previsoes

array([ 316587.33333333, 1724679.5       ,  533528.5       , ...,
        381863.5       ,  240535.        ,  203821.03      ])

In [27]:
y_casas_teste # faremos o comparativo com os dados reais.

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [28]:
previsoes[:20]

array([ 316587.33333333, 1724679.5       ,  533528.5       ,
        538340.9       ,  692361.65      ,  460343.8       ,
        322941.93      ,  329271.04      ,  430851.92      ,
       1953594.2       ,  837522.68      ,  402156.28      ,
        429289.        ,  270165.68      , 1012024.48      ,
        413815.        ,  456096.87      ,  696483.        ,
        473069.9       ,  355664.5       ])

In [29]:
y_casas_teste[:20]

array([ 297000., 1578000.,  562100.,  631500.,  780000.,  485000.,
        340000.,  335606.,  425000.,  490000.,  732000.,  389700.,
        450000.,  357000.,  960000.,  257000.,  448000.,  610000.,
        230950.,  377500.])

In [30]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste, previsoes)

67968.25418166023

In [31]:
# MAE

In [33]:


#BASE PREÇO DAS CASAS
# mae mean absolute error
# MAE  na regressão linear simples de: 172604.1288999541
# MAE  na regressão linear múltipla de: 123888.44377484299
# MAE  na regressão linear Polinomial de: 105307.1 
# MAE  na regressão linear Com árvore de decisão de: 99744.28423 
#MAE na regressão linear com Random Forest (mais de uma árvore de decisão 100) de: 67968.25418166023  ok
# quanto menor melhor. o MAE.
#pode errar 67968.25 para cima  para baixo.

# valor ok, até o momento este é o melhor.