# Projeto 9: Regressão carros usados - validação cruzada

## Etapa 1: Importação das bibliotecas

In [1]:
#!pip install skorch

In [2]:
import pandas as pd
import torch.nn as nn
from skorch import NeuralNetRegressor
import torch
from sklearn.model_selection import cross_val_score
import time
torch.__version__

'2.8.0+cu128'

## Etapa 2: Base de dados

In [5]:
# semente inicial
torch.manual_seed(123)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [6]:
base = pd.read_csv('autos.csv', encoding = 'ISO-8859-1')
display(base.tail())

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [7]:
# apagar alguns atributos que não são muito relevantes.


# datas no momento não nos interessa
#'dateCrawled',
#'dateCreated',
#'nrOfPictures', número de fotos não interfere
#'postalCode' no momento o cep não importa
#  'lastSeen' data da última visualização no site.

In [8]:
base = base.drop('dateCrawled', axis = 1)
base = base.drop('dateCreated', axis = 1)
base = base.drop('nrOfPictures', axis = 1)
base = base.drop('postalCode', axis = 1)
base = base.drop('lastSeen', axis = 1)
base = base.drop('name', axis = 1)
base = base.drop('seller', axis = 1)
base = base.drop('offerType', axis = 1)

In [9]:
# retirar os outliers
base = base[base.price > 10]
base = base.loc[base.price < 350000]

In [10]:
display(base.tail())

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371524,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN
371527,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [11]:
# preencher os dados nulos

valores = {'vehicleType': 'limousine', 'gearbox': 'manuell',
           'model': 'golf', 'fuelType': 'benzin',
           'notRepairedDamage': 'nein'}
base = base.fillna(value = valores)

In [12]:
previsores = base.iloc[:, 1:13].values
preco_real = base.iloc[:, 0].values.reshape(-1, 1)

In [14]:
list(base.columns[1:13]) # previsores

['abtest',
 'vehicleType',
 'yearOfRegistration',
 'gearbox',
 'powerPS',
 'model',
 'kilometer',
 'monthOfRegistration',
 'fuelType',
 'brand',
 'notRepairedDamage']

In [17]:
list(base.columns[:1]) # preço real

['price']

In [18]:
previsores

array([['test', 'limousine', 1993, ..., 'benzin', 'volkswagen', 'nein'],
       ['test', 'coupe', 2011, ..., 'diesel', 'audi', 'ja'],
       ['test', 'suv', 2004, ..., 'diesel', 'jeep', 'nein'],
       ...,
       ['test', 'bus', 1996, ..., 'diesel', 'volkswagen', 'nein'],
       ['test', 'kombi', 2002, ..., 'diesel', 'volkswagen', 'nein'],
       ['control', 'limousine', 2013, ..., 'benzin', 'bmw', 'nein']],
      dtype=object)

In [19]:
preco_real

array([[  480],
       [18300],
       [ 9800],
       ...,
       [ 9200],
       [ 3400],
       [28990]])

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehotencoder = ColumnTransformer(transformers = [("OneHot", OneHotEncoder(), [0,1,3,5,8,9,10])], remainder = 'passthrough')
previsores = onehotencoder.fit_transform(previsores).toarray()

In [21]:
previsores

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.02e+02, 1.50e+05, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+02, 1.50e+05, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 3.20e+02, 5.00e+04, 8.00e+00]])

In [22]:
previsores = previsores.astype('float32')
preco_real = preco_real.astype('float32')

In [23]:
previsores

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.02e+02, 1.50e+05, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+02, 1.50e+05, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 3.20e+02, 5.00e+04, 8.00e+00]],
      dtype=float32)

In [24]:
preco_real

array([[  480.],
       [18300.],
       [ 9800.],
       ...,
       [ 9200.],
       [ 3400.],
       [28990.]], dtype=float32)

## Etapa 3: Construção do modelo

In [25]:
len(previsores)

359291

In [27]:
previsores.shape # depois do onehotencoder  => neurônios do input

(359291, 316)

In [31]:
preco_real.shape  #=> neurônios de saída

(359291, 1)

In [29]:
# estimar os números de neurônios das camadas ocultas
(previsores.shape[1] + preco_real.shape[1])/2

158.5

## Etapa 3: Construção do modelo

In [32]:
# Definição da classe do modelo, herdando de nn.Module
#
class regressor_torch(nn.Module):
    def __init__(self):
        super().__init__()                         # inicializa a classe base (nn.Module)
        self.dense0 = nn.Linear(316, 158)          # camada totalmente conectada: 316 entradas ou 316 features → 158 neurônios nas camadas ocultas
        self.dense1 = nn.Linear(158, 158)          # segunda camada: 158 neurônios na primeira camada oculta → 158 neurônios na segunda camada oculta.
        self.dense2 = nn.Linear(158, 1)            # camada final: 158 na segunda camada oculta → 1 saída (previsão)
        self.activation = nn.ReLU()                # função de ativação ReLU (zera valores negativos)

    def forward(self, X):
        X = self.dense0(X)                         # passa os dados pela 1ª camada linear
        X = self.activation(X)                     # aplica ReLU
        X = self.dense1(X)                         # passa pela 2ª camada linear
        X = self.activation(X)                     # aplica ReLU de novo
        X = self.dense2(X)                         # passa pela camada final (gera saída predita)
        return X                                   # retorna a previsão


# Duas camadas escondidas: 158 neurônios cada, com ReLU
# Saída: 1 valor (regressão, ex.: previsão de vendas, preço etc.)


###                                         Camada de ativação

$\begin{array}{|c|c|c|c|}
\hline
\textbf{Função} & \textbf{Fórmula} & \textbf{Intervalo de saída} & \textbf{Uso comum} \\
\hline
\text{Sigmoid} & 
\sigma(x) = \frac{1}{1 + e^{-x}} & (0, 1) & \text{Classificação binária} \\
\hline
\text{Tanh} & 
\tanh(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}} & (-1, 1) & \text{Camadas ocultas (alternativa ao ReLU)} \\
\hline
\text{ReLU} & 
f(x) = \max(0, x) & [0, \infty) & \text{Camadas ocultas (mais usado)} \\
\hline
\text{Leaky ReLU} & 
f(x) = \begin{cases}
x & \text{se } x > 0 \\
\alpha x & \text{se } x \leq 0
\end{cases} & (-\infty, \infty) & \text{Evita neurônios mortos no ReLU} \\
\hline
\text{ELU} & 
f(x) = \begin{cases}
x & \text{se } x > 0 \\
\alpha(e^x - 1) & \text{se } x \leq 0
\end{cases} & (-\alpha, \infty) & \text{Camadas ocultas, alternativa ao ReLU} \\
\hline
\text{Softmax} & 
f(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}} & (0, 1), \ \sum f(x_i) = 1 & \text{Classificação multiclasse} \\
\hline
\end{array}$


🔹 O ReLU (Rectified Linear Unit)

Características:

Simples, rápido de calcular.

Resolve o problema do vanishing gradient (quando os gradientes ficam quase zero em sigmoides/tanh).

Muito usado em camadas ocultas.

⚠️ Problema: pode causar “neurônios mortos” (quando muitos valores ficam ≤ 0 e nunca mais reativam).

In [33]:
regressor_sklearn = NeuralNetRegressor(
    module = regressor_torch,          # minha classe de rede neural (definida antes)
    criterion = torch.nn.L1Loss,       # função de erro → MAE (erro absoluto médio)
    optimizer = torch.optim.Adam,      # otimizador → Adam (ajusta os pesos da rede)
    max_epochs = 100,                  # número máximo de épocas (vezes que o modelo "vê" os dados)
    batch_size = 300,                  # tamanho do lote de dados em cada iteração
    train_split = False                # não divide dados em treino/validação internamente, deixar para o sklearn
)

Resumindo:

NeuralNetRegressor → wrapper que deixa sua rede neural (regressor_torch) com a mesma interface de modelos do scikit-learn (fit, predict, score).

Vai treinar a rede com Adam, otimizando a perda L1Loss (MAE), durante até 100 épocas, em lotes de 300 amostras.

Como train_split=False, ele vai usar todos os dados de treino que você passar (sem separar validação automaticamente).

## Etapa 4: Validação cruzada


1) - Divide os dados em 5 partes (cv=5).

- Treina o modelo em 4 partes.

- Testa na parte restante.

- Repete o processo até todas as partes terem sido usadas como teste.

2) - Calcula a métrica em cada rodada.

- Como você escolheu 'neg_mean_absolute_error', o cross_val_score devolve o MAE negativo (isso é padrão no scikit-learn, porque algumas métricas precisam ser maximizadas).

3) - resultados → será um array com 5 valores, um para cada fold.

In [34]:
resultados = cross_val_score(
    regressor_sklearn,               # meu modelo (NeuralNetRegressor)
    previsores,                      # X → variáveis de entrada (features)
    preco_real,                      # y → variável alvo (valor real a prever) - (target)
    cv = 5,                          # validação cruzada k-fold com 5 divisões
    scoring = 'neg_mean_absolute_error'  # métrica: MAE (erro absoluto médio), mas em valor negativo
)

  epoch    train_loss      dur
-------  ------------  -------
      1     3576.3572  12.3829
      2     3002.0581  15.6682
      3     2856.8516  15.9557
      4     2813.6090  10.6570
      5     2741.3406  14.4750
      6     2750.2524  12.8946
      7     2690.5325  11.0509
      8     2668.2525  15.0420
      9     2683.1201  15.4444
     10     2599.6889  15.0638
     11     2576.4640  8.9591
     12     2557.8768  9.7248
     13     2533.6625  10.0214
     14     2518.3148  16.9227
     15     2508.3104  8.7621
     16     2507.2649  8.5554
     17     2488.9379  16.3574
     18     2479.8670  11.4221
     19     2460.5681  9.5805
     20     2450.9333  9.9913
     21     2476.1944  11.6099
     22     2460.0682  16.4916
     23     2430.4870  15.6230
     24     2424.7273  11.8253
     25     2418.2663  9.8970
     26     2426.1880  8.2794
     27     2419.0641  10.3937
     28     2425.7285  8.9330
     29     2416.7087  8.2381
     30     2405.1933  13.3005
     31     2386.5780  15.5851
     32     2398.4018  16.1240
     33     2401.1057  14.4105
     34     2396.4998  15.4884
     35     2398.8467  15.8798
     36     2379.3525  19.2283
     37     2386.4126  16.3463
     38     2376.8572  15.0650
     39     2376.1686  9.8304
     40     2377.5608  19.7358
     41     2369.1203  18.5648
     42     2376.4790  17.7927
     43     2365.5372  9.4932
     44     2362.8150  9.7554
     45     2375.3877  10.2131
     46     2362.8197  7.9959
     47     2371.5319  6.2841
     48     2377.3959  7.9955
     49     2359.1332  10.4529
     50     2360.0357  10.6263
     51     2349.3140  8.5899
     52     2365.5231  7.5691
     53     2359.2119  11.2004
     54     2351.7825  15.7318
     55     2347.8056  15.5491
     56     2353.2592  14.8923
     57     2343.2052  7.8891
     58     2346.9191  7.2227
     59     2350.2019  7.2801
     60     2367.9382  15.9943
     61     2366.8425  18.3715
     62     2343.9078  15.0771
     63     2342.2791  17.0644
     64     2339.3940  16.2575
     65     2337.7369  16.1784
     66     2332.7412  17.4337
     67     2335.7068  14.8705
     68     2340.9178  16.4052
     69     2333.6177  11.6341
     70     2339.9036  14.4629
     71     2330.2316  18.4129
     72     2324.1225  17.0256
     73     2321.6249  14.8179
     74     2337.6616  17.5637
     75     2319.9815  16.6649
     76     2321.5923  16.7453
     77     2322.6436  17.6603
     78     2323.5459  20.8654
     79     2311.7905  18.6291
     80     2318.3501  17.0448
     81     2312.6841  16.7520
     82     2317.4561  15.3502
     83     2316.1870  17.9088
     84     2311.7190  18.0338
     85     2315.2464  18.0263
     86     2312.0600  17.9399
     87     2310.0493  12.1088
     88     2307.4825  17.2695
     89     2304.3705  16.6344
     90     2311.7444  18.4929
     91     2303.5433  18.4111
     92     2307.9924  20.4394
     93     2299.9625  20.9141
     94     2298.0279  19.5987
     95     2302.7664  22.9596
     96     2295.8574  21.6918
     97     2300.2841  20.3118
     98     2292.8610  21.2815
     99     2305.7601  14.7360
    100     2294.2558  12.2531
  epoch    train_loss     dur
-------  ------------  ------
      1     3594.8199  6.4185
      2     2971.3088  13.1842
      3     2837.8019  21.5609
      4     2802.9929  18.2919
      5     2754.8377  15.8414
      6     2727.4100  17.1768
      7     2676.6085  13.0878
      8     2642.5817  12.9613
      9     2614.3498  17.7767
     10     2595.8254  17.6306
     11     2563.8524  20.8114
     12     2891.5449  22.1328
     13     2615.0725  23.7923
     14     2537.0705  25.9576
     15     2506.4015  24.3916
     16     2475.7715  20.8246
     17     2485.6597  25.9117
     18     2456.8680  22.0895
     19     2449.7946  16.6615
     20     2432.4582  10.6512
     21     2449.2905  9.3314
     22     2435.6351  18.2471
     23     2414.5241  17.7823
     24     2423.1877  12.0838
     25     2425.7110  16.2727
     26     2413.5874  37.0218
     27     2408.4715  17.2784
     28     2394.3159  18.6867
     29     2401.2440  21.4058
     30     2394.8972  17.6827
     31     2374.9714  15.7362
     32     2393.2208  14.5070
     33     2385.3836  13.3463
     34     2374.3233  13.5078
     35     2409.6193  12.1600
     36     2363.9780  16.1314
     37     2366.3594  16.1978
     38     2367.4297  15.9912
     39     2364.3116  13.3930
     40     2360.2713  3.0741
     41     2364.7632  2.9526
     42     2353.4192  2.8421
     43     2353.6810  3.7761
     44     2350.3534  4.6475
     45     2344.3243  7.5581
     46     2350.7159  7.6003
     47     2351.9362  8.3299
     48     2340.1173  7.4350
     49     2344.2182  8.1172
     50     2342.3154  7.7595
     51     2341.4133  7.7473
     52     2338.8318  8.6921
     53     2325.6218  7.9073
     54     2332.3713  7.9550
     55     2331.5178  7.6459
     56     2333.1116  6.7218
     57     2326.7208  8.1864
     58     2332.2110  9.1124
     59     2326.5909  4.2738
     60     2329.9809  4.2660
     61     2331.9612  4.3993
     62     2328.5469  8.7127
     63     2329.4414  8.1233
     64     2320.7584  8.6579
     65     2313.2744  8.3465
     66     2314.7955  8.6150
     67     2323.0416  10.0097
     68     2308.2264  9.2175
     69     2317.1764  9.4045
     70     2320.1335  9.2152
     71     2316.6996  9.1129
     72     2312.9104  9.2805
     73     2311.3760  10.7272
     74     2312.5120  10.6827
     75     2308.7010  9.7575
     76     2307.0219  10.6629
     77     2311.0563  12.0737
     78     2302.7307  12.1892
     79     2303.7639  8.3119
     80     2302.7811  9.8082
     81     2299.0833  9.7181
     82     2306.1187  12.3417
     83     2301.4551  7.7031
     84     2301.1256  10.1530
     85     2301.2648  13.1027
     86     2301.2989  10.8975
     87     2300.1521  10.6648
     88     2293.5909  13.1851
     89     2303.2176  10.1621
     90     2290.0637  13.0051
     91     2300.6762  12.4859
     92     2295.7362  12.1213
     93     2291.6011  12.1319
     94     2308.2636  12.0307
     95     2291.2431  5.0970
     96     2291.5317  9.9405
     97     2281.9803  12.2438
     98     2286.5333  13.1004
     99     2295.6360  12.7766
    100     2288.2665  10.7643
  epoch    train_loss     dur
-------  ------------  ------
      1     3569.8145  6.8812
      2     3003.3089  10.0447
      3     2899.7078  9.5029
      4     2810.9050  9.2107
      5     2753.2828  9.3105
      6     2719.0077  4.9202
      7     2686.7480  5.2306
      8     2701.0877  4.9191
      9     2615.4383  7.2107
     10     2608.7784  7.4894
     11     3316.5240  6.9978
     12     3003.9059  4.6081
     13     2778.0008  7.6608
     14     2619.5916  7.8284
     15     2565.9627  7.8758
     16     2535.5367  7.1375
     17     2519.7951  8.0446
     18     2504.1288  7.4848
     19     2484.1842  7.6054
     20     2483.1702  7.9021
     21     2479.7010  7.2672
     22     2463.5088  7.6571
     23     2446.4393  7.8968
     24     2456.3128  7.6908
     25     2445.7515  5.2264
     26     2438.4420  4.0457
     27     2448.6879  4.5852
     28     2421.5368  4.3932
     29     2421.4337  7.9241
     30     2430.6382  7.3630
     31     2434.1686  7.2524
     32     2411.2891  7.7166
     33     2413.2629  8.1093
     34     2419.4760  7.8992
     35     2411.4008  5.0536
     36     2402.2804  6.3924
     37     2393.7223  7.3229
     38     2387.9035  7.1612
     39     2394.7574  7.7115
     40     2396.7831  8.0762
     41     2385.7592  7.8173
     42     2401.7621  4.1565
     43     2389.8399  4.0345
     44     2387.0084  4.0247
     45     2385.5804  6.7307
     46     2381.9649  8.2248
     47     2398.8868  4.4558
     48     2382.0813  4.8362
     49     2377.3084  5.5325
     50     2378.6675  4.4090
     51     2375.1166  3.9861
     52     2366.0059  4.2414
     53     2374.9264  5.3318
     54     2375.3840  4.4917
     55     2371.1265  7.1359
     56     2372.3870  7.8728
     57     2372.4942  7.3813
     58     2367.9491  8.0647
     59     2375.4974  8.2434
     60     2368.5736  7.0376
     61     2366.9610  3.3123
     62     2364.5196  3.3051
     63     2367.4990  4.6009
     64     2361.0809  4.9099
     65     2353.2388  5.8864
     66     2360.1052  8.3058
     67     2356.1912  7.8561
     68     2353.1536  8.8997
     69     2345.5208  8.3040
     70     2359.9587  8.1936
     71     2351.5472  8.3924
     72     2341.4403  8.9749
     73     2341.7115  7.0419
     74     2393.1474  4.5614
     75     2354.4059  4.9443
     76     2349.7272  5.2710
     77     2342.6578  5.4302
     78     2352.2017  5.1698
     79     2339.5406  5.1585
     80     2342.0928  4.6771
     81     2339.4100  7.7438
     82     2339.1056  9.4501
     83     2340.1570  9.1652
     84     2338.4085  8.6787
     85     2333.2173  9.4210
     86     2341.0498  9.4053
     87     2340.3657  8.4445
     88     2335.6021  9.0103
     89     2334.1549  9.4576
     90     2333.5060  9.1207
     91     2326.7725  9.0620
     92     2327.2403  9.5697
     93     2332.7838  9.4436
     94     2332.7977  9.5378
     95     2322.5936  4.6205
     96     2323.1337  5.1847
     97     2324.1705  4.8571
     98     2322.1800  3.4866
     99     2334.7873  3.4990
    100     2317.7244  3.5836
  epoch    train_loss     dur
-------  ------------  ------
      1     3632.5836  2.7254
      2     2997.8121  2.9933
      3     2884.2468  2.7378
      4     2842.5518  3.1617
      5     2805.4606  3.1976
      6     2723.7515  4.2541
      7     2692.8230  4.4423
      8     2669.2899  4.0889
      9     2629.3501  3.3204
     10     2606.6174  3.1069
     11     2590.1877  2.9708
     12     2542.2566  2.9082
     13     2528.5677  4.3105
     14     2548.0088  4.2951
     15     2494.5484  4.4029
     16     2495.7456  4.2871
     17     2481.7381  4.3998
     18     2482.1142  4.0766
     19     2467.5909  3.8989
     20     2460.7572  3.8167
     21     2447.8689  3.2069
     22     2449.2148  4.2473
     23     2457.5374  4.3999
     24     2450.9903  4.2367
     25     2439.3316  4.1987
     26     2426.8728  3.8840
     27     2442.8727  4.0636
     28     2423.2821  4.3055
     29     2426.0870  4.3782
     30     2427.1861  5.5481
     31     2413.6569  7.8193
     32     2420.0107  7.9949
     33     2419.3791  7.3485
     34     2409.2130  7.2827
     35     2402.4221  4.6579
     36     2409.2413  7.9693
     37     2416.8006  8.1136
     38     2402.2656  3.9685
     39     2395.7044  4.4650
     40     2397.7852  4.6070
     41     2395.8135  4.5093
     42     2395.8549  4.1001
     43     2387.7212  5.4206
     44     2388.5096  8.1072
     45     2391.1662  7.3610
     46     2378.7192  7.6059
     47     2381.2518  8.2213
     48     2383.4708  8.2388
     49     2366.5886  7.4017
     50     2381.7989  7.8985
     51     2370.1745  8.1326
     52     2375.1383  8.1225
     53     2366.8272  7.3538
     54     2371.1065  8.0395
     55     2374.1062  3.6986
     56     2367.5100  3.4088
     57     2362.5647  3.4572
     58     2364.1193  4.9859
     59     2367.5519  7.5467
     60     2364.7163  8.4447
     61     2357.7137  7.6276
     62     2359.1363  8.1773
     63     2357.5387  8.5339
     64     2357.7634  8.7905
     65     2357.5033  7.9623
     66     2350.0775  8.8902
     67     2338.4652  7.9750
     68     2350.7661  8.3328
     69     2348.5995  8.7966
     70     2349.8604  8.9680
     71     2348.8856  5.2046
     72     2355.8167  4.6982
     73     2345.5189  5.2382
     74     2340.9024  5.3316
     75     2337.9680  5.4700
     76     2343.6870  9.1567
     77     2345.2154  8.9056
     78     2333.7000  8.7835
     79     2334.8014  9.5527
     80     2334.5782  9.2951
     81     2330.7071  8.5773
     82     2338.8476  6.1417
     83     2332.4551  5.8365
     84     2331.4205  4.9159
     85     2331.6262  5.3466
     86     2327.2436  5.4722
     87     2333.5306  5.3679
     88     2337.3438  5.5369
     89     2326.3086  6.3837
     90     2333.5536  9.1800
     91     2330.9081  10.0033
     92     2324.0295  9.5896
     93     2329.1000  9.3294
     94     2332.6071  10.1667
     95     2318.1755  8.4022
     96     2327.0591  9.8761
     97     2343.7962  9.4905
     98     2326.8828  9.7367
     99     2316.8757  9.4810
    100     2335.2767  10.2088
  epoch    train_loss     dur
-------  ------------  ------
      1     3547.7090  5.3625
      2     2999.7672  3.8721
      3     2898.9303  5.4559
      4     2831.3160  7.8997
      5     2798.6936  7.9437
      6     2767.8402  7.5636
      7     2687.5852  7.0966
      8     2688.2368  4.6856
      9     2647.3482  7.9258
     10     2608.7267  6.6578
     11     2583.7482  7.0402
     12     2559.8221  7.2690
     13     2564.3422  7.8608
     14     2539.2950  7.2376
     15     2523.9872  4.8102
     16     2511.9061  3.4255
     17     2502.0054  3.2034
     18     2507.4831  3.2310
     19     2490.5748  3.3376
     20     2485.6867  3.7086
     21     2482.1731  3.7179
     22     2474.8187  3.7595
     23     2476.1579  4.1171
     24     2460.8121  4.4123
     25     2483.4109  4.1865
     26     2451.8311  4.3106
     27     2453.7131  4.3057
     28     2438.1434  6.1386
     29     2447.4970  6.3374
     30     2430.5022  4.2836
     31     2448.7949  4.2065
     32     2440.8831  3.7575
     33     2431.4234  4.0064
     34     2419.5705  4.3097
     35     2440.7566  4.1477
     36     2427.0295  5.1169
     37     2416.3165  8.0631
     38     2416.3453  4.2329
     39     2420.1220  4.1614
     40     2420.5748  5.7983
     41     2400.3068  7.4821
     42     2400.0660  7.2195
     43     2394.7364  7.2253
     44     2396.6450  7.9760
     45     2402.3394  7.9698
     46     2383.6390  7.4130
     47     2398.7176  7.6160
     48     2386.3223  4.2899
     49     2392.1334  4.3070
     50     2421.8920  4.3783
     51     2384.0897  4.3031
     52     2369.0752  4.3533
     53     2385.4391  4.1486
     54     2399.9157  4.2724
     55     2372.8851  4.3516
     56     2366.3393  3.9939
     57     2365.2728  5.1091
     58     2360.9156  4.3143
     59     2365.1643  4.4071
     60     2352.4345  4.4805
     61     2353.3689  7.8062
     62     2356.4662  7.8946
     63     2365.5235  7.9042
     64     2361.0369  8.4650
     65     2353.6654  8.2789
     66     2352.1631  7.9781
     67     2348.7192  6.1933
     68     2344.9394  4.8565
     69     2357.0024  4.8095
     70     2357.5063  4.9199
     71     2337.4425  4.8909
     72     2337.6716  7.8023
     73     2338.5248  7.4288
     74     2339.1580  8.4601
     75     2335.0732  8.6488
     76     2336.2865  9.1408
     77     2335.6473  8.4693
     78     2337.9636  9.3136
     79     2333.8571  8.3727
     80     2331.6609  8.9236
     81     2329.3352  9.2551
     82     2323.6533  7.2951
     83     2342.0707  5.4298
     84     2327.5830  8.9518
     85     2332.5666  8.8515
     86     2322.2869  9.6427
     87     2316.9781  4.8437
     88     2320.8531  5.2530
     89     2320.6627  4.9416
     90     2324.5167  3.9876
     91     2320.0454  3.4249
     92     2312.5218  3.4588
     93     2312.4034  3.6425
     94     2326.1143  3.8937
     95     2308.3051  4.5496
     96     2312.9370  4.4583
     97     2319.1000  4.6573
     98     2323.6847  6.6530
     99     2313.1544  9.7750
    100     2315.4626  8.2632

In [36]:
media = resultados.mean()
desvio = resultados.std()

print(f'MAE médio {media} e com o desvio {desvio}')

MAE médio -2358.42626953125 e com o desvio 146.52189116046165