# 5.9) Indução das Regras

In [1]:
#bibliotema do algoritmo e interface gráfica

In [3]:
#!pip install Orange3

# Base risco de crédito

##### teremos que mudar a coluna para c#risco para que o dado seja se considera como a classe. Anotação no .csv, para o origem interpretar esses dados.

In [8]:
import pandas as pd
df_base_risco_credito = pd.read_csv('../4-Bayesiana/risco_credito.csv') 
display(df_base_risco_credito.tail())

df_base_risco_credito = df_base_risco_credito.rename(columns={'risco': 'c#risco'})
df_base_risco_credito.head()

   historia divida garantias     renda     risco
9       boa   alta  adequada  acima_35     baixo
10      boa   alta   nenhuma      0_15      alto
11      boa   alta   nenhuma     15_35  moderado
12      boa   alta   nenhuma  acima_35     baixo
13     ruim   alta   nenhuma     15_35      alto

       historia divida garantias     renda   c#risco
0          ruim   alta   nenhuma      0_15      alto
1  desconhecida   alta   nenhuma     15_35      alto
2  desconhecida  baixa   nenhuma     15_35  moderado
3  desconhecida  baixa   nenhuma  acima_35      alto
4  desconhecida  baixa   nenhuma  acima_35     baixo

In [10]:
df_base_risco_credito.to_csv('risco_credito_regras.csv', sep=';', index= False)

In [11]:
# coletar os dados no formato orange
import Orange


base_risco_credito = Orange.data.Table('risco_credito_regras.csv') # correto risco de crédito regras
base_risco_credito

[[ruim, alta, nenhuma, 0_15 | alto],
 [desconhecida, alta, nenhuma, 15_35 | alto],
 [desconhecida, baixa, nenhuma, 15_35 | moderado],
 [desconhecida, baixa, nenhuma, acima_35 | alto],
 [desconhecida, baixa, nenhuma, acima_35 | baixo],
 ...
]

1) o c# se separa com | , ficamos com 4 previsores e 1 classe depois do |

2) ver o domínio

In [12]:
base_risco_credito.domain

[historia, divida, garantias, renda | risco]

https://orange.readthedocs.io/en/latest/reference/rst/Orange.classification.rules.html

In [14]:
# cn2 algoritmo 
cn2 = Orange.classification.rules.CN2Learner() # algorimo baseado em regras
regras_risco_credito = cn2(base_risco_credito) # criando as regras
# com isso treinamento já foi concluido

In [15]:
for regras in regras_risco_credito.rule_list:
  print(regras) # geradas as regras

IF renda==0_15 THEN risco=alto
IF historia==boa AND divida!=alta THEN risco=baixo
IF historia==boa AND garantias!=nenhuma THEN risco=baixo
IF historia==boa AND renda!=15_35 THEN risco=baixo
IF historia==boa THEN risco=moderado
IF divida==alta THEN risco=alto
IF historia!=desconhecida THEN risco=moderado
IF garantias==adequada THEN risco=baixo
IF renda==15_35 THEN risco=moderado
IF historia==desconhecida THEN risco=baixo
IF TRUE THEN risco=alto

simulação de dois registros

In [16]:
# história boa, dívida alta, garantias nenhuma, renda > 35
# história ruim, dívida alta, garantias adequada, renda < 15

In [18]:
# história boa (0), dívida alta (0), garantias nenhuma (1), renda > 35 (2)
# história ruim (2), dívida alta (0), garantias adequada (0), renda < 15 (0)

# algoritmo consegue trabalhar com os atributos categóricos
previsoes = regras_risco_credito([['boa', 'alta', 'nenhuma', 'acima_35'], ['ruim', 'alta', 'adequada', '0_15']])
previsoes

array([1, 0])

In [19]:
# verificar a classe
base_risco_credito.domain.class_var

DiscreteVariable(name='risco'name='risco',
                 ,
                 values=('alto', 'baixo', 'moderado')values=('alto',
                  'baixo',
                  'moderado'))

In [20]:
base_risco_credito.domain.class_var.values

('alto', 'baixo', 'moderado')

In [21]:
# ver a associação entre os nomes
for i in previsoes:
  print(i)
  print(base_risco_credito.domain.class_var.values[i])

1
baixo
0
alto

In [22]:
# ver a associação entre os nomes
for i in previsoes:
  #print(i)
  print(base_risco_credito.domain.class_var.values[i])

baixo
alto


## simulação na regra inteira 

## 1)  história boa, dívida alta, garantias nenhuma, renda > 35

IF renda==0_15 THEN risco=alto x

IF historia==boa AND divida!=alta THEN risco=baixo x

IF historia==boa AND garantias!=nenhuma THEN risco=baixo x

IF historia==boa AND renda!=15_35 THEN risco=baixo ok

IF historia==boa THEN risco=moderado 

IF divida==alta THEN risco=alto 

IF historia!=desconhecida THEN risco=moderado 

IF garantias==adequada THEN risco=baixo 

IF renda==15_35 THEN risco=moderado 

IF historia==desconhecida THEN risco=baixo 

IF TRUE THEN risco=alto



## 2)  história ruim, dívida alta, garantias adequada, renda < 15

JÁ NA PRIMEIRA REGRA

IF renda==0_15 THEN risco=alto OK

IF historia==boa AND divida!=alta THEN risco=baixo 

IF historia==boa AND garantias!=nenhuma THEN risco=baixo 

IF historia==boa AND renda!=15_35 THEN risco=baixo 

IF historia==boa THEN risco=moderado 

IF divida==alta THEN risco=alto 

IF historia!=desconhecida THEN risco=moderado 

IF garantias==adequada THEN risco=baixo 

IF renda==15_35 THEN risco=moderado 

IF historia==desconhecida THEN risco=baixo 

IF TRUE THEN risco=alto (default- padrão)