# 6.1) Indução das Regras - Base Crédito

In [1]:
# colocaremos como i#clientid será ignorado
# será usado o income, age, loan, 
# a classe será c#default

In [6]:
import pandas as pd
base_credit = pd.read_csv('../2-3-Classificacao/credit_risk_dataset.csv') 
display(base_credit.tail())

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [7]:

base_credit = base_credit[['person_income', 'person_age', 'loan_amnt', 'loan_status']]

base_credit['person_income'] = base_credit['person_income'].astype('float')
base_credit['person_age'] = base_credit['person_age'].astype('float')
base_credit['loan_amnt'] = base_credit['loan_amnt'].astype('float')

base_credit = base_credit.reset_index()
base_credit = base_credit.rename(columns={"index": "clientid"})
base_credit.tail()

       clientid  person_income  person_age  loan_amnt  loan_status
32576     32576        53000.0        57.0     5800.0            0
32577     32577       120000.0        54.0    17625.0            0
32578     32578        76000.0        65.0    35000.0            1
32579     32579       150000.0        56.0    15000.0            0
32580     32580        42000.0        66.0     6475.0            0

In [8]:
# colocaremos como i#clientid que será ignorado
# será usado o person_income, person_age, loan_amnt, 
# a classe será c#default -> c#loan_status -> se a pessoa vai ou nã pagar o impréstimo 

df_base_credit = base_credit.rename(columns={'loan_status': 'c#loan_status', 'clientid': 'i#clientid'})
df_base_credit.head()
df_base_credit.to_csv('risco_credit_data_rules.csv', sep=';', index= False)

In [9]:
# coletar os dados no formato orange
import Orange

base_credit = Orange.data.Table('risco_credit_data_rules.csv')
# correto risco de crédito regras
base_credit

[[59000.0, 22.0, 35000.0 | 1],
 [9600.0, 21.0, 1000.0 | 0],
 [9600.0, 25.0, 5500.0 | 1],
 [65500.0, 23.0, 35000.0 | 1],
 [54400.0, 24.0, 35000.0 | 1],
 ...
]

In [10]:
# ver a separação correta dos atributos
base_credit.domain
# [income, age, loan | default]

[person_income, person_age, loan_amnt | loan_status]

In [11]:

# parâmetro n é base de dados de teste, com valor de 0.25 -> 25% para  testar e 75% para treinar
# foi criado uma matriz

base_dividida = Orange.evaluation.testing.sample(base_credit, n = 0.25)
base_dividida

([[42348.0, 25.0, 8000.0 | 0],
  [48000.0, 42.0, 3500.0 | 0],
  [44700.0, 22.0, 4000.0 | 0],
  [83000.0, 24.0, 25000.0 | 0],
  [80000.0, 26.0, 7000.0 | 0],
  ...
 ],
 [[87000.0, 23.0, 8000.0 | 0],
  [51400.0, 32.0, 8000.0 | 0],
  [33000.0, 22.0, 1400.0 | 0],
  [46000.0, 24.0, 10000.0 | 0],
  [39000.0, 25.0, 16000.0 | 1],
  ...
 ])

In [12]:
base_dividida[0] #primira parte da base de dados

[[42348.0, 25.0, 8000.0 | 0],
 [48000.0, 42.0, 3500.0 | 0],
 [44700.0, 22.0, 4000.0 | 0],
 [83000.0, 24.0, 25000.0 | 0],
 [80000.0, 26.0, 7000.0 | 0],
 ...
]

In [13]:
base_dividida[1] # segunda parte da base de dados

[[87000.0, 23.0, 8000.0 | 0],
 [51400.0, 32.0, 8000.0 | 0],
 [33000.0, 22.0, 1400.0 | 0],
 [46000.0, 24.0, 10000.0 | 0],
 [39000.0, 25.0, 16000.0 | 1],
 ...
]

In [15]:
base_treinamento = base_dividida[1]
base_teste = base_dividida[0]

In [16]:
# ver o tamanho dos dados
len(base_treinamento), len(base_teste)

(24436, 8145)

In [17]:
cn2 = Orange.classification.rules.CN2Learner()
regras_credit = cn2(base_treinamento)  # criar as regras com base do treinamento

c#loan_status -> se a pessoa vai ou nã pagar o impréstimo 

Pessoa paga o empréstimo -> 0 

Pessoa NÃO PAGA O EMPRÉSTIMO -> 1

In [18]:
# conjunto de regras gerados 
for regras in regras_credit.rule_list:
  print(regras)

IF person_income>=69867.0 AND person_income<=70500.0 AND person_age>=35.0 THEN loan_status=0
IF person_income>=69867.0 AND person_income<=70550.0 AND person_income>=70550.0 AND person_age>=23.0 THEN loan_status=1
IF person_income>=79995.0 AND loan_amnt<=22200.0 AND person_income<=80004.0 AND person_age>=31.0 THEN loan_status=0
IF person_income>=79995.0 AND loan_amnt<=22200.0 AND person_income<=80004.0 AND loan_amnt>=10750.0 THEN loan_status=0
IF person_income>=68850.0 AND loan_amnt<=15000.0 AND person_age>=63.0 THEN loan_status=0
IF person_income>=74872.0 AND loan_amnt<=22200.0 AND person_income<=75500.0 AND loan_amnt>=19600.0 THEN loan_status=0
IF person_income>=69867.0 AND loan_amnt<=19200.0 AND person_income<=70500.0 AND loan_amnt<=14500.0 AND loan_amnt>=14500.0 THEN loan_status=1
IF person_income>=79996.0 AND loan_amnt<=22200.0 AND person_income<=80004.0 AND loan_amnt<=5000.0 AND person_age>=26.0 THEN loan_status=0
IF person_income>=74872.0 AND loan_amnt<=19200.0 AND person_income>=84175.0 AND person_income<=85500.0 AND person_age<=26.0 THEN loan_status=0
IF person_income>=58617.0 AND person_income<=58700.0 AND person_age>=24.0 THEN loan_status=1
IF person_income>=74872.0 AND loan_amnt<=19200.0 AND person_income>=88500.0 AND person_income<=91992.0 AND person_age>=27.0 THEN loan_status=0
IF person_income>=92000.0 AND person_income<=96050.0 AND person_income>=96050.0 AND person_age>=25.0 THEN loan_status=1
IF person_income>=89523.0 AND person_income<=92000.0 AND person_income>=92000.0 AND person_age>=29.0 THEN loan_status=0
IF person_income>=92000.0 AND person_income<=100300.0 AND loan_amnt<=19800.0 AND person_age>=60.0 THEN loan_status=1
IF person_income>=92000.0 AND person_income<=100300.0 AND loan_amnt<=19800.0 AND loan_amnt>=19800.0 THEN loan_status=1
IF person_income>=89523.0 AND loan_amnt<=22200.0 AND loan_amnt<=7500.0 AND person_age>=49.0 THEN loan_status=0
IF person_income>=89523.0 AND loan_amnt<=22200.0 AND person_income<=91800.0 AND person_income>=91800.0 AND person_age>=24.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50820.0 AND person_age>=54.0 THEN loan_status=1
IF person_income>=89523.0 AND person_income<=91800.0 AND loan_amnt<=24625.0 AND loan_amnt>=24625.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50820.0 AND loan_amnt<=15600.0 AND person_age>=32.0 THEN loan_status=0
IF person_income>=89523.0 AND loan_amnt<=22200.0 AND person_income<=91000.0 AND loan_amnt>=5175.0 AND person_income>=90096.0 THEN loan_status=0
IF person_income>=89523.0 AND person_age<=27.0 AND person_income<=91000.0 AND loan_amnt>=16000.0 THEN loan_status=0
IF person_income>=89523.0 AND person_income<=91000.0 AND person_age<=47.0 AND person_age>=47.0 THEN loan_status=1
IF person_income>=89523.0 AND person_income<=91000.0 AND person_age>=28.0 THEN loan_status=0
IF person_income>=89523.0 AND person_age<=27.0 AND loan_amnt<=22350.0 AND loan_amnt>=22350.0 THEN loan_status=1
IF person_income>=89523.0 AND loan_amnt<=23000.0 AND person_age<=27.0 AND loan_amnt<=19750.0 AND loan_amnt>=19750.0 THEN loan_status=1
IF person_income>=89523.0 AND loan_amnt<=23000.0 AND person_age<=27.0 AND person_age<=22.0 AND person_income>=115000.0 THEN loan_status=0
IF person_income>=89523.0 AND person_age<=27.0 AND person_income<=91000.0 AND person_age>=26.0 AND loan_amnt>=5175.0 THEN loan_status=0
IF person_income>=89523.0 AND person_age<=27.0 AND person_income<=91000.0 AND loan_amnt>=15000.0 AND person_age>=24.0 THEN loan_status=0
IF person_income>=89523.0 AND person_age<=27.0 AND person_income<=91000.0 AND person_income>=91000.0 AND loan_amnt>=5000.0 THEN loan_status=1
IF person_income>=89523.0 AND person_income<=91800.0 AND loan_amnt<=15000.0 AND person_income>=91000.0 THEN loan_status=0
IF person_income>=89523.0 AND person_income<=91800.0 AND loan_amnt<=15000.0 AND person_age>=24.0 THEN loan_status=0
IF person_income>=90000.0 AND loan_amnt<=23000.0 AND loan_amnt<=19975.0 AND person_age>=65.0 THEN loan_status=1
IF person_income>=90000.0 AND person_income<=100300.0 AND person_income>=98700.0 AND loan_amnt<=21000.0 AND loan_amnt>=21000.0 THEN loan_status=1
IF person_income>=90000.0 AND person_income<=100300.0 AND loan_amnt<=20000.0 AND person_income>=98700.0 AND loan_amnt<=8400.0 THEN loan_status=0
IF person_income>=90000.0 AND person_age<=27.0 AND person_income>=264000.0 THEN loan_status=0
IF person_income>=49995.0 AND person_income<=50820.0 AND loan_amnt<=15600.0 AND loan_amnt>=15600.0 THEN loan_status=1
IF person_income>=90000.0 AND loan_amnt<=23000.0 AND loan_amnt<=19975.0 AND loan_amnt>=19975.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50820.0 AND loan_amnt<=15850.0 AND person_age<=23.0 AND person_income>=50004.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=218000.0 AND person_income>=198171.0 AND person_age<=26.0 AND loan_amnt>=10000.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=136000.0 AND person_income>=118075.0 AND person_income<=120600.0 AND person_age>=32.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=97583.0 AND loan_amnt<=20000.0 AND person_age>=29.0 AND loan_amnt>=16000.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=19200.0 AND person_income>=79272.0 AND person_age>=56.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=19200.0 AND person_income>=79272.0 AND loan_amnt>=18550.0 THEN loan_status=0
IF person_income>=60000.0 AND person_income<=60072.0 AND loan_amnt<=18500.0 AND person_age<=23.0 AND loan_amnt<=13000.0 THEN loan_status=0
IF person_income>=54860.0 AND person_income<=55044.0 AND person_age>=41.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=18500.0 AND person_income<=60072.0 AND person_age>=44.0 THEN loan_status=0
IF person_income>=49995.0 AND person_income<=50100.0 AND loan_amnt<=15850.0 AND person_age<=31.0 AND loan_amnt>=15850.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50100.0 AND loan_amnt<=16000.0 AND person_age<=35.0 AND person_age>=35.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50100.0 AND loan_amnt<=16000.0 AND person_age>=50.0 THEN loan_status=1
IF person_income>=54860.0 AND loan_amnt<=15000.0 AND person_income<=55080.0 AND loan_amnt>=7000.0 AND loan_amnt>=10200.0 THEN loan_status=0
IF person_income>=54400.0 AND person_income<=54480.0 AND person_age>=25.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50100.0 AND loan_amnt<=16000.0 AND person_age<=23.0 AND loan_amnt<=7200.0 THEN loan_status=0
IF person_income>=54050.0 AND loan_amnt<=15000.0 AND person_income>=79100.0 AND loan_amnt<=7500.0 AND person_income>=240000.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=213000.0 AND person_income>=198171.0 AND person_age>=28.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=188000.0 AND person_income>=188000.0 AND person_age>=32.0 THEN loan_status=1
IF person_income>=90000.0 AND loan_amnt<=23000.0 AND person_age<=28.0 AND person_income<=190000.0 AND person_income>=172500.0 THEN loan_status=0
IF person_income>=90000.0 AND person_age<=27.0 AND person_income<=131400.0 AND person_income>=119500.0 AND loan_amnt>=25000.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=136000.0 AND person_income>=118189.0 AND person_income<=120600.0 AND loan_amnt<=8000.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=136000.0 AND person_income>=119500.0 AND person_income<=120600.0 AND loan_amnt>=14400.0 THEN loan_status=0
IF person_income>=83954.0 AND loan_amnt<=23000.0 AND loan_amnt<=18500.0 AND person_income<=108000.0 AND person_age>=46.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=107000.0 AND loan_amnt<=20000.0 AND person_income>=103089.0 AND person_income>=105201.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=105400.0 AND person_income>=105400.0 AND loan_amnt>=24250.0 THEN loan_status=1
IF person_income>=90000.0 AND loan_amnt<=23000.0 AND person_age<=27.0 AND loan_amnt>=20400.0 AND person_income>=108000.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=105400.0 AND person_income>=104800.0 AND person_age>=26.0 AND person_age>=29.0 THEN loan_status=0
IF person_income>=74872.0 AND loan_amnt<=18500.0 AND person_income<=75805.0 AND loan_amnt>=14125.0 THEN loan_status=0
IF person_income>=79996.0 AND loan_amnt<=22200.0 AND person_age<=53.0 AND person_age>=53.0 THEN loan_status=1
IF person_income>=79996.0 AND loan_amnt<=22200.0 AND person_income<=80004.0 AND person_age<=25.0 AND loan_amnt>=6500.0 THEN loan_status=0
IF person_income>=56160.0 AND loan_amnt<=18125.0 AND person_income>=84175.0 AND person_income<=85500.0 AND person_age>=28.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=96050.0 AND person_income>=93080.0 AND person_age>=48.0 THEN loan_status=1
IF person_income>=90000.0 AND person_income<=96050.0 AND person_age<=22.0 AND person_income>=93218.0 THEN loan_status=0
IF person_income>=90000.0 AND person_income<=97583.0 AND person_income>=93080.0 AND person_age>=24.0 AND person_age<=25.0 THEN loan_status=0
IF person_income>=56996.0 AND loan_amnt<=18125.0 AND person_income>=88500.0 AND loan_amnt<=7500.0 AND person_age>=48.0 THEN loan_status=1
IF person_income>=90000.0 AND person_income<=191250.0 AND person_income<=91800.0 AND loan_amnt<=15000.0 THEN loan_status=0
IF person_income>=93132.0 AND person_income<=96000.0 AND loan_amnt<=24000.0 AND person_age>=34.0 THEN loan_status=0
IF person_income>=93132.0 AND person_income<=96000.0 AND person_age<=37.0 AND person_age>=37.0 THEN loan_status=1
IF person_income>=93132.0 AND person_income<=96000.0 AND person_age<=28.0 AND person_age>=28.0 THEN loan_status=0
IF person_income>=100300.0 AND person_income>=108820.0 AND person_income<=110400.0 AND loan_amnt>=15250.0 THEN loan_status=0
IF person_income>=100300.0 AND person_age<=27.0 AND loan_amnt<=23000.0 AND loan_amnt>=23000.0 THEN loan_status=1
IF person_income>=100300.0 AND person_income>=108820.0 AND person_income<=110400.0 AND person_age<=29.0 AND person_income>=110000.0 THEN loan_status=0
IF person_income>=98056.0 AND person_income<=100300.0 AND loan_amnt<=24250.0 AND person_income>=99996.0 AND loan_amnt>=10300.0 THEN loan_status=0
IF person_income>=113135.0 AND person_income<=116000.0 AND person_age<=23.0 AND person_income>=114600.0 THEN loan_status=0
IF person_income>=113135.0 AND person_income<=116000.0 AND person_age>=23.0 AND person_age>=41.0 THEN loan_status=0
IF person_income>=113135.0 AND loan_amnt<=22200.0 AND person_income<=116000.0 AND loan_amnt>=15000.0 THEN loan_status=0
IF person_income>=118189.0 AND loan_amnt<=22000.0 AND person_income<=131400.0 AND loan_amnt>=22000.0 THEN loan_status=1
IF person_income>=118189.0 AND loan_amnt<=22200.0 AND person_income<=125375.0 AND loan_amnt>=15200.0 THEN loan_status=0
IF person_income>=118189.0 AND person_income<=136000.0 AND loan_amnt<=24250.0 AND person_income>=134400.0 AND person_age>=30.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=15000.0 AND person_age<=22.0 AND loan_amnt>=12200.0 AND person_income>=69867.0 THEN loan_status=0
IF person_income>=118189.0 AND person_income<=133000.0 AND person_income>=123144.0 AND person_income<=125375.0 AND person_age>=29.0 THEN loan_status=0
IF person_income>=49200.0 AND loan_amnt<=14800.0 AND person_income<=53826.0 AND person_age>=45.0 THEN loan_status=0
IF person_income>=56996.0 AND loan_amnt<=18125.0 AND person_income<=58617.0 AND person_age>=51.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50650.0 AND person_age<=38.0 AND person_age>=38.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50650.0 AND person_age<=33.0 AND person_age>=33.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50650.0 AND person_age<=43.0 AND person_age>=43.0 THEN loan_status=1
IF person_income>=49995.0 AND person_income<=50650.0 AND person_age>=26.0 AND person_age>=36.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=15000.0 AND person_age<=22.0 AND person_income<=62050.0 AND loan_amnt>=6325.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=15000.0 AND person_age<=22.0 AND loan_amnt<=3200.0 AND person_income>=71004.0 THEN loan_status=0
IF person_income>=49995.0 AND person_income<=50650.0 AND person_age<=26.0 AND loan_amnt<=16000.0 AND person_age>=26.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=15000.0 AND person_income<=60072.0 AND person_age<=36.0 AND loan_amnt>=8500.0 THEN loan_status=0
IF person_income>=108820.0 AND person_income<=112800.0 AND person_age>=32.0 THEN loan_status=0
IF person_income>=118189.0 AND person_income<=191250.0 AND loan_amnt<=22200.0 AND loan_amnt>=22200.0 THEN loan_status=1
IF person_income>=118189.0 AND loan_amnt<=23000.0 AND loan_amnt<=9000.0 AND person_age>=54.0 THEN loan_status=1
IF person_income>=118189.0 AND loan_amnt<=23000.0 AND person_age>=46.0 THEN loan_status=0
IF person_income>=118189.0 AND loan_amnt<=23000.0 AND loan_amnt<=10000.0 AND person_age>=37.0 THEN loan_status=0
IF person_income>=50000.0 AND person_income<=50650.0 AND person_age>=29.0 AND loan_amnt<=16000.0 AND person_age<=30.0 THEN loan_status=0
IF person_income>=60000.0 AND loan_amnt<=15000.0 AND person_income<=60072.0 AND loan_amnt<=8400.0 AND person_age>=37.0 THEN loan_status=0
IF person_income>=64777.0 AND person_income<=65007.0 AND loan_amnt<=18000.0 AND person_age>=26.0 THEN loan_status=0
IF person_income>=75500.0 AND loan_amnt<=18500.0 AND person_age>=55.0 THEN loan_status=1
IF person_income>=69383.0 AND person_income<=70500.0 AND person_income>=70000.0 AND loan_amnt<=17000.0 AND person_income>=70004.0 THEN loan_status=0
IF person_income>=74880.0 AND loan_amnt<=18500.0 AND person_income<=75805.0 AND loan_amnt<=13450.0 AND loan_amnt>=13450.0 THEN loan_status=1
IF person_income>=74880.0 AND loan_amnt<=18500.0 AND person_income<=75905.0 AND loan_amnt>=18000.0 THEN loan_status=1
IF person_income>=69383.0 AND loan_amnt<=18500.0 AND person_income<=70550.0 AND person_age<=24.0 AND loan_amnt>=1600.0 THEN loan_status=0
IF person_income>=79000.0 AND person_income>=118189.0 AND person_income<=133000.0 AND person_income>=130000.0 AND person_age>=33.0 THEN loan_status=0
IF person_income>=79000.0 AND loan_amnt<=18500.0 AND loan_amnt<=11200.0 AND loan_amnt>=10200.0 AND person_age>=32.0 THEN loan_status=0
IF person_income>=79000.0 AND loan_amnt<=18500.0 AND person_income<=82800.0 AND person_income>=81004.0 AND person_age>=24.0 THEN loan_status=0
IF person_income>=79000.0 AND loan_amnt<=23000.0 AND person_income>=118300.0 AND person_income<=120600.0 AND person_age<=27.0 THEN loan_status=0
IF person_income>=79000.0 AND person_income>=124896.0 AND person_income<=125375.0 AND person_age>=25.0 THEN loan_status=0
IF person_income>=79000.0 AND loan_amnt<=23000.0 AND person_income>=138996.0 AND person_income<=142800.0 AND person_age>=26.0 THEN loan_status=0
IF person_income>=60000.0 AND person_income>=149400.0 AND person_income<=150500.0 AND person_age>=27.0 THEN loan_status=0
IF person_income>=50000.0 AND loan_amnt<=14800.0 AND person_income<=50100.0 AND person_age<=25.0 AND loan_amnt<=12000.0 THEN loan_status=0
IF person_income<=20000.0 AND person_age>=62.0 THEN loan_status=0
IF person_income<=20000.0 AND loan_amnt>=2750.0 AND loan_amnt>=6500.0 AND person_age>=23.0 THEN loan_status=1
IF loan_amnt<=9250.0 AND person_income>=58617.0 AND person_age>=26.0 AND person_age>=54.0 THEN loan_status=0
IF loan_amnt<=13200.0 AND person_income>=44412.0 AND person_income<=45630.0 AND person_income>=45630.0 AND loan_amnt>=4000.0 THEN loan_status=1
IF loan_amnt<=9250.0 AND person_income>=60000.0 AND person_income<=60072.0 AND loan_amnt<=2000.0 AND person_age>=28.0 THEN loan_status=0
IF loan_amnt<=9250.0 AND person_income>=60000.0 AND person_income<=60072.0 AND loan_amnt>=3050.0 AND person_age>=30.0 THEN loan_status=0
IF person_income<=20000.0 AND loan_amnt>=2750.0 AND loan_amnt>=16600.0 THEN loan_status=0
IF loan_amnt<=9250.0 AND person_income>=34942.0 AND loan_amnt>=9125.0 AND person_income>=61476.0 THEN loan_status=0
IF person_income<=20000.0 AND loan_amnt>=2750.0 AND loan_amnt<=4800.0 AND person_age>=38.0 THEN loan_status=1
IF person_income<=20000.0 AND loan_amnt>=2750.0 AND person_age>=43.0 THEN loan_status=0
IF person_income<=20000.0 AND person_age>=49.0 THEN loan_status=1
IF loan_amnt<=9175.0 AND person_income>=60000.0 AND person_income<=62050.0 AND person_income>=62050.0 AND person_age>=24.0 THEN loan_status=1
IF loan_amnt<=13200.0 AND person_income>=39960.0 AND person_income<=40500.0 AND loan_amnt<=12500.0 AND loan_amnt>=12500.0 THEN loan_status=1
IF loan_amnt<=13200.0 AND person_income>=39960.0 AND person_income<=40500.0 AND loan_amnt<=12800.0 AND loan_amnt>=12800.0 THEN loan_status=1
IF loan_amnt<=8875.0 AND person_income>=60000.0 AND person_income>=144000.0 AND person_age>=31.0 AND loan_amnt>=7200.0 THEN loan_status=0
IF loan_amnt<=13200.0 AND person_income>=54503.0 AND loan_amnt<=7450.0 AND person_income<=55080.0 AND loan_amnt<=5000.0 THEN loan_status=0
IF loan_amnt<=13200.0 AND person_income>=56996.0 AND person_income<=58313.0 AND loan_amnt>=11400.0 THEN loan_status=0
IF loan_amnt<=9175.0 AND person_income>=60000.0 AND person_income<=62540.0 AND loan_amnt<=1700.0 AND person_age>=24.0 THEN loan_status=0
IF person_income>=59068.0 AND loan_amnt<=7450.0 AND loan_amnt<=5050.0 AND person_age>=42.0 THEN loan_status=0
IF loan_amnt<=9175.0 AND person_income>=58617.0 AND person_income>=59196.0 AND person_income<=59600.0 AND person_age>=26.0 THEN loan_status=0
IF person_income>=60785.0 AND loan_amnt<=15000.0 AND person_income>=69780.0 AND person_income<=72644.0 AND person_age>=52.0 THEN loan_status=1
IF person_income>=60785.0 AND loan_amnt<=15000.0 AND person_income>=69780.0 AND person_income<=72644.0 AND person_age>=38.0 THEN loan_status=0
IF loan_amnt<=9175.0 AND person_income>=60000.0 AND person_age<=22.0 AND loan_amnt<=3200.0 AND loan_amnt>=3200.0 THEN loan_status=1
IF person_income>=59068.0 AND loan_amnt<=7450.0 AND loan_amnt<=5050.0 AND person_income>=140000.0 AND loan_amnt>=3800.0 THEN loan_status=0
IF person_income>=59068.0 AND loan_amnt<=18500.0 AND person_income>=74880.0 AND person_income<=75996.0 AND loan_amnt<=14000.0 THEN loan_status=0
IF person_income>=79000.0 AND person_income>=149400.0 AND person_income<=150500.0 AND loan_amnt>=12000.0 THEN loan_status=0
IF loan_amnt<=9175.0 AND person_income>=34942.0 AND person_income<=35050.0 AND loan_amnt<=2400.0 AND person_income>=35004.0 THEN loan_status=0
IF person_income>=79000.0 AND person_income<=105400.0 AND loan_amnt<=18500.0 AND person_income>=98004.0 AND person_income>=103089.0 THEN loan_status=0
IF person_income>=35000.0 AND loan_amnt<=11550.0 AND loan_amnt>=11550.0 THEN loan_status=1
IF person_income>=79000.0 AND person_income>=153600.0 AND person_age<=22.0 AND person_income>=160000.0 THEN loan_status=0
IF loan_amnt<=13200.0 AND person_income>=39960.0 AND person_income<=40500.0 AND person_income>=40000.0 AND person_age<=24.0 THEN loan_status=0
IF person_income>=35000.0 AND loan_amnt<=11600.0 AND person_income>=79100.0 AND loan_amnt>=11600.0 THEN loan_status=1
IF person_income>=79000.0 AND loan_amnt<=23000.0 AND person_income<=102616.0 AND person_income>=98004.0 AND person_age>=45.0 THEN loan_status=1
IF person_income>=35000.0 AND loan_amnt<=11700.0 AND person_income>=79100.0 AND loan_amnt>=11400.0 THEN loan_status=0
IF person_income>=35000.0 AND loan_amnt<=11700.0 AND person_income>=79100.0 AND loan_amnt>=11375.0 THEN loan_status=1
IF person_income>=79000.0 AND loan_amnt<=23000.0 AND person_income<=102616.0 AND person_income>=98004.0 AND person_age>=35.0 THEN loan_status=0
IF person_income>=79000.0 AND loan_amnt<=23000.0 AND person_income<=80004.0 AND loan_amnt<=4000.0 AND person_income>=79100.0 THEN loan_status=0
IF person_income>=79000.0 AND person_income>=153600.0 AND person_age<=23.0 AND person_income>=159996.0 AND loan_amnt>=15000.0 THEN loan_status=0

person_income -> renda

person_age -> ano

loan_amnt -> empréstimo

In [19]:

# executar em sequência

fazer as previsões na base de teste

In [20]:
previsoes = Orange.evaluation.testing.TestOnTestData(base_treinamento, base_teste, [lambda testdata: regras_credit])
# passar as bases de treinamento, base teste, e o tempo de execução: nome do algoritmo

# executar o teste

In [21]:
previsoes # classe no formato Results

In [22]:
#classification accuracy

#F1, visutalizar 

Orange.evaluation.CA(previsoes)

array([0.82676489])

# Acurácia de 82,7% no base credit

In [30]:

print(f'Acurácia do modelo {Orange.evaluation.CA(previsoes)[0]*100:.2f} %')

Acurácia do modelo 82.68 %

In [32]:
# acurácia
# comparando com a outra árvore de decisão da base de crédito -> 3-2_Arvore_decisao_parte3_basecredito.ipynb
# a acurácia foi de 81.57 %.
# random forest (muitas árvores) acurácia de 84,21% -> 3-4_Arvore_decision_Random_Forest.ipynb

# Base census será utilizado a interface gráfica do Orange

https://orangedatamining.com/

https://orangedatamining.com/download/